namespace KitPlatform.Packs.Content;

/// <summary>Narrative DNA V1 for the six KIT Marketing brands. Seeded onto pack_content.brand.narrative_json.</summary>
public static class BrandNarrativeCatalog
{
    public static IReadOnlyList<BrandNarrativeDna> All { get; } =
    [
        KitTech(),
        Novixa(),
        Famixa(),
        VanDinhTra(),
        XuanHoa(),
        ThaiNguyenLife(),
    ];

    public static BrandNarrativeDna ByCode(string code) =>
        All.First(d => string.Equals(d.BrandCode, code, StringComparison.OrdinalIgnoreCase));

    public static string BuildMigrationSql()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("-- KitPlatform 371: Brand Narrative DNA V1");
        sb.AppendLine("-- Manifest: deploy/ubuntu/migration-files.content.txt");
        sb.AppendLine("-- Adds narrative_json on pack_content.brand. Does not touch series, episodes, or content packages.");
        sb.AppendLine();
        sb.AppendLine("ALTER TABLE pack_content.brand");
        sb.AppendLine("    ADD COLUMN IF NOT EXISTS narrative_json JSONB NOT NULL DEFAULT '{}'::jsonb;");
        sb.AppendLine();
        sb.AppendLine("COMMENT ON COLUMN pack_content.brand.narrative_json IS");
        sb.AppendLine("    'Authoritative Brand Narrative DNA. Operational brief must not override territory decisions.';");
        sb.AppendLine();
        foreach (var dna in All)
        {
            var json = BrandNarrativeFit.Serialize(dna).Replace("$narrative$", "$ narrative $", StringComparison.Ordinal);
            sb.AppendLine("UPDATE pack_content.brand");
            sb.AppendLine("SET narrative_json = $narrative$" + json + "$narrative$::jsonb,");
            sb.AppendLine("    updated_at = NOW()");
            sb.AppendLine("WHERE code = '" + dna.BrandCode + "';");
            sb.AppendLine();
        }

        sb.AppendLine("UPDATE pack_content.brand");
        sb.AppendLine("SET default_cta_url = 'https://thainguyenlife.vn',");
        sb.AppendLine("    updated_at = NOW()");
        sb.AppendLine("WHERE code = 'tnlife'");
        sb.AppendLine("  AND COALESCE(default_cta_url, '') NOT ILIKE '%thainguyenlife.vn%';");
        sb.AppendLine();
        return sb.ToString();
    }

    private static NarrativeTerritory T(
        string id, string name, string type, string description, string why, string audience,
        string[] examples, string[] boundaries, int priority) =>
        new(id, name, type, description, why, audience, examples, boundaries, priority);

    private static BrandNarrativeDna KitTech() => new(
        1, "kittech",
        "Technology has value when it becomes a real operational system.",
        ["Founder", "Chủ doanh nghiệp", "Đội ngũ vận hành", "Đối tác triển khai", "Người đang xây sản phẩm số"],
        [],
        [
            T("kittech.core.building-real-systems", "Building Real Systems", "core",
                "Cách xây sản phẩm, platform và hệ thống có thể vận hành thật.",
                "KIT kể chuyện từ bài toán thực tế thành hệ thống đang chạy, không kể AI kỳ diệu.",
                "Người xây và vận hành hệ thống",
                ["Những quyết định nhỏ trong thiết kế hệ thống có thể quyết định khả năng vận hành của cả doanh nghiệp."],
                ["Không dừng ở slogan công nghệ."], 1),
            T("kittech.core.operational-intelligence", "Operational Intelligence", "core",
                "Biến dữ liệu và quy trình thành năng lực vận hành.",
                "Dữ liệu chỉ có giá trị khi nó đổi cách vận hành.",
                "Đội vận hành",
                ["Quy trình và dữ liệu trở thành năng lực vận hành đo được."],
                ["Không báo cáo số liệu cho có."], 2),
            T("kittech.core.ai-applied-to-real-work", "AI Applied to Real Work", "core",
                "AI được đưa vào những công việc cụ thể thay vì chỉ nói về AI như một xu hướng.",
                "AI thuộc KIT khi nó làm một việc vận hành cụ thể.",
                "Người xây sản phẩm",
                ["AI làm một công việc vận hành cụ thể, không phải xu hướng."],
                ["Không viết AI như tin tức xu hướng."], 3),
            T("kittech.core.product-platform-thinking", "Product & Platform Thinking", "core",
                "Tư duy xây platform, module, ecosystem và sản phẩm có khả năng mở rộng.",
                "KIT xây nền tảng và module, không bán một tính năng rời.",
                "Founder và đối tác triển khai",
                ["Platform, module và hệ sinh thái sản phẩm có thể mở rộng."],
                ["Không biến thành catalogue tính năng."], 4),
            T("kittech.supporting.founder-journey", "Founder journey", "supporting",
                "Hành trình người xây sản phẩm.",
                "Chỉ khi nó chiếu vào cách xây hệ thống.",
                "Founder", ["Founder đang biến một bài toán thành hệ thống."], ["Không nhật ký cá nhân."], 10),
            T("kittech.supporting.product-development", "Product development", "supporting",
                "Cách làm sản phẩm.", "Mở rộng chuyện xây hệ thống.", "Đội sản phẩm",
                ["Phát triển sản phẩm từ bài toán vận hành."], ["Không tutorial rời brand."], 11),
            T("kittech.supporting.engineering", "Engineering", "supporting",
                "Văn hoá và thực hành kỹ thuật.", "Khi nó phục vụ hệ thống vận hành được.", "Kỹ sư",
                ["Engineering culture gắn với hệ thống chạy thật."], ["Không khoe stack."], 12),
            T("kittech.supporting.automation", "Automation", "supporting",
                "Tự động hoá công việc thật.", "Automation là một cách biến công nghệ thành vận hành.", "Đội vận hành",
                ["Tự động hoá một quy trình đang làm bằng tay."], ["Không hứa thay toàn bộ con người."], 13),
            T("kittech.supporting.digital-transformation", "Digital transformation", "supporting",
                "Chuyển đổi số nhìn từ người xây hệ thống.", "Chỉ khi gắn với vận hành thật.", "Chủ doanh nghiệp",
                ["Chuyển đổi số là xây hệ thống vận hành, không phải mua công cụ."], ["Không slogan chuyển đổi số."], 14),
            T("kittech.supporting.multi-brand-operations", "Multi-brand operations", "supporting",
                "Vận hành nhiều brand trên một nền.", "Đúng với cách KIT xây park.", "Đối tác triển khai",
                ["Một nền tảng vận hành nhiều brand mà không trộn giọng."], ["Không gộp sáu brand thành một bài."], 15),
            T("kittech.adjacent.ai-trends", "AI trends", "adjacent",
                "Xu hướng AI.", "Chỉ khi nhìn từ người xây và vận hành hệ thống.", "Người xây sản phẩm",
                ["Xu hướng AI được kéo về một việc vận hành cụ thể."], ["Không tin công nghệ thuần."], 20),
            T("kittech.adjacent.business-technology", "Business technology", "adjacent",
                "Công nghệ trong doanh nghiệp.", "Phải gắn với hệ thống vận hành.", "Chủ doanh nghiệp",
                ["Công nghệ doanh nghiệp nhìn từ năng lực vận hành."], ["Không roundup tin công nghệ."], 21),
            T("kittech.adjacent.startup-lessons", "Startup/product lessons", "adjacent",
                "Bài học sản phẩm.", "Từ góc người xây hệ thống.", "Founder",
                ["Bài học startup gắn với cách vận hành sản phẩm."], ["Không tâm sự khởi nghiệp chung."], 22),
            T("kittech.adjacent.future-of-work", "Future of work", "adjacent",
                "Tương lai của việc làm và công cụ.", "Chỉ từ góc người xây hệ thống.", "Đội vận hành",
                ["Việc làm tương lai khi công cụ trở thành hệ thống."], ["Không dự báo xã hội chung."], 23),
            T("kittech.off.ai-hype", "AI hype", "off-brand",
                "AI hype thuần túy.", "KIT không kể chuyện AI kỳ diệu.", "—",
                ["AI kỳ diệu sẽ thay đổi mọi thứ mà không có việc cụ thể."], ["Không có bài toán vận hành."], 90),
            T("kittech.off.generic-tech-news", "Generic technology news", "off-brand",
                "Tin công nghệ không gắn với công việc thực tế.", "KIT không phải trang tin công nghệ.", "—",
                ["Tin công nghệ tổng hợp trong tuần."], ["Không liên hệ hệ thống đang xây."], 91),
            T("kittech.off.unsupported-revenue", "Unsupported revenue promises", "off-brand",
                "Cam kết doanh thu không có evidence.", "Không hứa số tiền.", "—",
                ["Cam kết tăng doanh thu X% nhờ AI."], ["Không evidence."], 92),
            T("kittech.off.ai-replaces-everyone", "AI replaces everyone", "off-brand",
                "AI thay thế toàn bộ con người.", "KIT không kể chuyện thay hết nhân sự.", "—",
                ["AI thay thế toàn bộ con người trong doanh nghiệp."], ["Không phải chuyện vận hành có người."], 93),
        ],
        ["Đừng nói công nghệ có thể làm gì. Hãy cho thấy nó giải quyết một vấn đề vận hành như thế nào."],
        "Một trang tin AI/công nghệ tổng hợp.");

    private static BrandNarrativeDna Novixa() => new(
        1, "novixa",
        "Selling every day does not mean operating well.",
        ["Chủ nhà thuốc", "Chủ chuỗi nhỏ", "Dược sĩ quản lý", "Người chịu trách nhiệm kho, dòng tiền và vận hành"],
        [],
        [
            T("novixa.core.pharmacy-operations", "Pharmacy Operations", "core",
                "Những vấn đề thật đang xảy ra tại quầy thuốc: kho, quy trình, dữ liệu, nhân sự.",
                "Novixa bắt đầu từ vết nứt vận hành, không từ việc bán phần mềm.",
                "Chủ nhà thuốc",
                ["Những lỗi nhỏ trong quản lý kho có thể âm thầm làm thất thoát lợi nhuận nhà thuốc."],
                ["Không mở bài bằng POS hay bảng giá phần mềm."], 1),
            T("novixa.core.inventory-fefo", "Inventory & FEFO", "core",
                "Tồn kho, lô, hạn dùng, vòng quay, hàng chậm bán, FEFO.",
                "Kho và hạn dùng là chuyện Novixa có lý do để kể.",
                "Dược sĩ quản lý kho",
                ["Hàng chậm bán và lệch FEFO làm đọng vốn trong kho nhà thuốc."],
                ["Không biến thành SOP kho generic ngoài nhà thuốc."], 2),
            T("novixa.core.cashflow-loss", "Cash Flow & Loss Prevention", "core",
                "Dòng tiền, giao ca, công nợ, thất thoát, quỹ và doanh thu nhà thuốc.",
                "Bán được hàng chưa có nghĩa là tiền và vận hành đang khỏe.",
                "Chủ nhà thuốc",
                ["Doanh thu đều nhưng quỹ và dòng tiền nhà thuốc vẫn hụt."],
                ["Không cam kết lãi."], 3),
            T("novixa.core.customer-retention", "Customer Retention", "core",
                "Dữ liệu khách hàng, khách cũ, chăm sóc và quay lại mua thuốc.",
                "Khách quay lại là một phần vận hành nhà thuốc.",
                "Chủ nhà thuốc",
                ["Khách cũ không quay lại vì nhà thuốc không có dữ liệu chăm sóc."],
                ["Không phải marketing generic."], 4),
            T("novixa.core.standardized-management", "Standardized Pharmacy Management", "core",
                "Chuẩn hóa quy trình và vận hành không phụ thuộc một cá nhân.",
                "Nhà thuốc chạy được khi chủ vắng mặt là chuyện vận hành.",
                "Chủ chuỗi nhỏ",
                ["Nhà thuốc vẫn chạy đúng quy trình khi chủ không đứng quầy."],
                ["Không thành truyện quản trị chung."], 5),
            T("novixa.supporting.gpp", "GPP", "supporting",
                "Thực hành tốt nhà thuốc.", "GPP là chuẩn vận hành nhà thuốc.", "Dược sĩ quản lý",
                ["GPP trong vận hành kho và quầy."], ["Không giáo trình pháp chế rời quầy."], 10),
            T("novixa.supporting.hr", "HR", "supporting",
                "Nhân sự quầy thuốc.", "Khi gắn với vận hành và thất thoát.", "Chủ nhà thuốc",
                ["Giao ca và nhân sự làm lệch quỹ."], ["Không tuyển dụng."], 11),
            T("novixa.supporting.expansion", "Pharmacy expansion", "supporting",
                "Mở rộng chuỗi nhỏ.", "Chỉ sau khi một quầy vận hành không rò.", "Chủ chuỗi nhỏ",
                ["Mở cơ sở hai khi quy trình kho và dòng tiền chưa chuẩn."], ["Không cổ vũ mở chuỗi."], 12),
            T("novixa.supporting.reports", "Reports", "supporting",
                "Báo cáo quản trị nhà thuốc.", "Báo cáo phải chỉ việc cần làm, không chỉ doanh thu.", "Chủ nhà thuốc",
                ["Báo cáo nhà thuốc chỉ doanh thu mà không chỉ lỗ vận hành."], ["Không dashboard khoe số."], 13),
            T("novixa.supporting.pharmacy-technology", "Pharmacy technology", "supporting",
                "Công nghệ nhà thuốc.", "Chỉ khi nó phục vụ vận hành quầy, kho, dòng tiền.", "Chủ nhà thuốc",
                ["Phần mềm nhà thuốc đang làm thêm việc thay vì bớt việc vận hành."], ["Không review phần mềm chung."], 14),
            T("novixa.supporting.phc", "Pharmacy Health Check", "supporting",
                "Pharmacy Health Check, bài chẩn đoán vận hành 7 phút.",
                "PHC là cách nhìn vết nứt trước khi bán công cụ.",
                "Chủ nhà thuốc",
                ["Pharmacy Health Check cho chủ nhà thuốc thấy vết nứt vận hành."],
                ["Không biến PHC thành landing bán POS."], 15),
            T("novixa.adjacent.pharmacy-marketing", "Pharmacy marketing", "adjacent",
                "Marketing nhà thuốc.", "Phải quay lại bài toán vận hành.", "Chủ nhà thuốc",
                ["Marketing nhà thuốc khi vận hành kho và khách đang rò."], ["Không mẹo bán hàng."], 20),
            T("novixa.adjacent.industry-trends", "Pharmacy industry trends", "adjacent",
                "Xu hướng ngành dược.", "Chỉ khi kéo về vận hành nhà thuốc.", "Chủ chuỗi nhỏ",
                ["Xu hướng ngành dược nhìn từ vận hành quầy."], ["Không tin ngành chung."], 21),
            T("novixa.adjacent.buyer-behavior", "Buyer behavior", "adjacent",
                "Hành vi người mua thuốc.", "Phải thành chuyện dữ liệu và vận hành.", "Dược sĩ quản lý",
                ["Hành vi khách mua thuốc và dữ liệu khách quay lại."], ["Không tâm lý học chung."], 22),
            T("novixa.adjacent.digital", "Digital transformation", "adjacent",
                "Chuyển đổi số khi gắn với vận hành nhà thuốc.", "Không phải công nghệ chung.", "Chủ nhà thuốc",
                ["Chuyển đổi số nhà thuốc bắt đầu từ kho, quỹ và quy trình."], ["Không bài công nghệ không có quầy thuốc."], 23),
            T("novixa.off.diagnosis", "Diagnosis and treatment", "off-brand",
                "Nội dung chữa bệnh, chẩn đoán.", "Novixa không khám bệnh.", "—",
                ["Cách chữa bệnh và chẩn đoán triệu chứng."], ["Không kê đơn."], 90),
            T("novixa.off.drug-sales", "Drug sales comparisons", "off-brand",
                "So sánh thuốc theo hướng bán hàng.", "Không dùng nội dung để đẩy thuốc.", "—",
                ["So sánh thuốc nào bán chạy hơn để nhập thêm."], ["Không bảng xếp hạng thuốc."], 91),
            T("novixa.off.politics", "Politics", "off-brand",
                "Chính trị.", "Ngoài chuyện nhà thuốc.", "—",
                ["Bình luận chính trị."], ["Không."], 92),
            T("novixa.off.generic-tech", "Generic technology", "off-brand",
                "Công nghệ chung không liên quan nhà thuốc. Trà, việc làm thành phố, Family OS.",
                "Novixa không kể chuyện ngoài vận hành nhà thuốc.",
                "—",
                ["Cách pha một ấm trà ngon.", "Tin công nghệ không có quầy thuốc."],
                ["Không cưỡng angle nhà thuốc cho chủ đề khác ngành."], 93),
        ],
        ["Đừng bắt đầu bằng việc bán phần mềm. Hãy bắt đầu bằng việc giúp chủ nhà thuốc nhìn thấy vấn đề."],
        "Một website bán phần mềm POS.");

    private static BrandNarrativeDna Famixa() => new(
        1, "famixa",
        "FamilyOS for families with children; a child grows from the small things a family does every day.",
        ["Bố mẹ có con", "Cha mẹ bận rộn", "Cha mẹ muốn con tự lập hơn"],
        ["Ông bà khi tham gia nuôi dạy trẻ", "Vợ chồng", "Người chăm sóc trẻ", "Thành viên gia đình có vai trò nuôi dạy trẻ"],
        [
            T("famixa.core.parenting", "Parenting & Child Development", "core",
                "Cha mẹ đồng hành với con trong quá trình trưởng thành. Trẻ em là trung tâm.",
                "Famixa kể cách một gia đình có con nuôi dưỡng và đồng hành cùng đứa trẻ.",
                "Bố mẹ có con",
                ["Những điều nhỏ bé mỗi ngày tạo nên cách một đứa trẻ lớn lên."],
                ["Không bài gia đình không có trẻ."], 1),
            T("famixa.core.habits", "Habits & Routines", "core",
                "Những thói quen nhỏ của gia đình có con tạo nên năng lực của trẻ.",
                "Thói quen thuộc Famixa khi nó hình thành con người đứa trẻ.",
                "Cha mẹ bận rộn",
                ["Thói quen nhỏ cha mẹ tạo ra mỗi ngày đang hình thành tính tự lập của con."],
                ["Thói quen người lớn không gắn với trẻ thì không thuộc core."], 2),
            T("famixa.core.responsibility", "Responsibility & Independence", "core",
                "Giúp trẻ học cách tự làm, tự nhớ, tự chịu trách nhiệm.",
                "Tự lập của trẻ là chuyện Famixa có lý do để kể.",
                "Cha mẹ muốn con tự lập hơn",
                ["Trẻ học tự làm và tự chịu trách nhiệm từ việc nhỏ trong nhà."],
                ["Không thành kỹ năng sống người lớn."], 3),
            T("famixa.core.communication", "Parent–Child Communication", "core",
                "Lắng nghe, giao tiếp và kết nối giữa cha mẹ và con.",
                "Cách nói với con là chuyện nuôi dạy.",
                "Bố mẹ có con",
                ["Cha mẹ lắng nghe và nói với con thay vì chỉ nhắc việc."],
                ["Không giao tiếp vợ chồng tách khỏi trẻ."], 4),
            T("famixa.core.family-life", "Family Life With Children", "core",
                "Những tình huống đời thường trong gia đình có con.",
                "Đời sống gia đình thuộc Famixa khi có trẻ ở trung tâm.",
                "Gia đình có con",
                ["Một buổi tối trong gia đình có con và việc nhà cùng làm."],
                ["Không lifestyle gia đình chung."], 5),
            T("famixa.supporting.grandparents", "Grandparents in Family System", "supporting",
                "Ông bà trong hệ thống nuôi dạy trẻ: khác thế hệ, phối hợp người lớn, ảnh hưởng lên đứa trẻ.",
                "Ông bà chỉ được kể khi câu chuyện ảnh hưởng cách nuôi dạy trẻ. Ông bà không phải trung tâm nội dung.",
                "Ông bà và cha mẹ cùng nuôi dạy trẻ",
                [
                    "Ông bà có một cách rất khác khi dạy trẻ.",
                    "Ông bà tham gia hình thành thói quen cho trẻ.",
                    "Khi ông bà và cha mẹ khác nhau trong cách dạy trẻ, đứa trẻ sẽ học điều gì?",
                ],
                ["Không bài sức khỏe hay đời sống người cao tuổi tách khỏi trẻ."], 10),
            T("famixa.supporting.marriage", "Parents & Marriage", "supporting",
                "Quan hệ cha mẹ khi ảnh hưởng đến trẻ.",
                "Hôn nhân chỉ thuộc Famixa nếu đứa trẻ chịu ảnh hưởng.",
                "Vợ chồng có con",
                ["Cha mẹ bất đồng cách dạy và con nhìn thấy điều đó."],
                ["Không chuyện tình cảm người lớn."], 11),
            T("famixa.supporting.school", "School & Child", "supporting",
                "Nhà trường, học tập và đời sống của trẻ.",
                "Trường học thuộc hành trình trưởng thành của trẻ.",
                "Bố mẹ có con",
                ["Việc học của con và cách cha mẹ đồng hành sau giờ học."],
                ["Không tin giáo dục chung."], 12),
            T("famixa.supporting.environment", "Family Environment", "supporting",
                "Môi trường gia đình ảnh hưởng sự trưởng thành của trẻ.",
                "Không khí nhà là một phần nuôi dạy.",
                "Gia đình có con",
                ["Môi trường trong nhà ảnh hưởng cách một đứa trẻ lớn."],
                ["Không nội thất hay lifestyle."], 13),
            T("famixa.adjacent.work-stress", "Parent work and stress", "adjacent",
                "Công việc và áp lực của cha mẹ.",
                "Phải có liên hệ rõ với gia đình có con.",
                "Cha mẹ bận rộn",
                ["Áp lực công việc của cha mẹ làm ngắn thời gian ở bên con."],
                ["Không bài năng suất cá nhân."], 20),
            T("famixa.adjacent.family-health", "Family health", "adjacent",
                "Sức khỏe gia đình có con.", "Phải gắn với trẻ hoặc cách nuôi con.", "Bố mẹ có con",
                ["Sức khỏe của con trong nhịp sinh hoạt gia đình."], ["Không chữa bệnh. Không sức khỏe người già tách khỏi trẻ."], 21),
            T("famixa.adjacent.finance", "Family finance", "adjacent",
                "Tài chính gia đình có con.", "Phải liên hệ việc nuôi dạy hoặc nhịp nhà có trẻ.", "Cha mẹ",
                ["Chi tiêu gia đình và điều con học được về trách nhiệm."], ["Không tư vấn đầu tư."], 22),
            T("famixa.adjacent.multigen", "Multigenerational life", "adjacent",
                "Đời sống nhiều thế hệ.", "Chỉ khi liên hệ gia đình có con hoặc hành trình của trẻ.", "Gia đình có con",
                ["Nhà nhiều thế hệ và cách người lớn phối hợp để nuôi một đứa trẻ."],
                ["Không chuyên đề người cao tuổi."], 23),
            T("famixa.off.pure-elderly", "Pure elderly content", "off-brand",
                "Nội dung thuần người cao tuổi.",
                "Ông bà không được thành một kênh nội dung riêng.",
                "—",
                ["7 thói quen tốt cho người cao tuổi.", "7 thói quen giúp người cao tuổi sống khỏe hơn."],
                ["Không liên hệ trẻ, cha mẹ, hoặc gia đình có con."], 90),
            T("famixa.off.elderly-health", "Pure elderly health", "off-brand",
                "Chăm sóc sức khỏe người cao tuổi không liên quan trẻ.",
                "Sức khỏe người già không phải chuyện Famixa nếu không đi qua đứa trẻ.",
                "—",
                ["Chăm sóc sức khỏe người cao tuổi mà không nhắc trẻ hay cha mẹ."],
                ["Không bài bệnh người già."], 91),
            T("famixa.off.generic-lifestyle", "Generic family lifestyle", "off-brand",
                "Lifestyle gia đình chung chung, không có quan hệ với trẻ.",
                "Famixa không phải trang tổng hợp mọi thứ về gia đình.",
                "—",
                ["Lifestyle gia đình chung không có đứa trẻ."], ["Không."], 92),
            T("famixa.off.travel", "Generic family travel", "off-brand",
                "Du lịch gia đình thuần túy.", "Đi chơi không tự động là chuyện nuôi dạy.", "—",
                ["Lịch trình du lịch gia đình không gắn với trẻ lớn lên."], ["Không."], 93),
            T("famixa.off.no-child", "No child relation", "off-brand",
                "Nội dung không có liên hệ với trẻ, cha mẹ hoặc hệ thống gia đình có con.",
                "Không có câu trả lời cho cách gia đình nuôi dưỡng đứa trẻ thì không thuộc Famixa.",
                "—",
                ["Một chủ đề gia đình không nhắc trẻ, cha mẹ, hay nuôi dạy."], ["Không."], 94),
        ],
        [
            "Mỗi câu chuyện Famixa phải trả lời được: điều này ảnh hưởng gì đến cách một gia đình nuôi dưỡng, hỗ trợ, giao tiếp, hoặc giúp một đứa trẻ lớn lên?",
            "Ông bà khác cách dạy trẻ là SUPPORTING. Thói quen người cao tuổi không gắn với trẻ là OFF-BRAND. Dữ liệu cũ về chăm sóc người già không được làm authority.",
        ],
        "Một trang tổng hợp mọi thứ về gia đình, hoặc một kênh nội dung về người cao tuổi.",
        new NarrativeGuard(
            ["người cao tuổi", "người già"],
            ["dạy trẻ", "đứa trẻ", "trẻ em", "cha mẹ", "bố mẹ", "con cái"]));

    private static BrandNarrativeDna VanDinhTra() => new(
        1, "vandinhtra",
        "Vietnamese tea, region, culture and the slow tea ritual. Tinh hoa trà từ đỉnh mây.",
        ["Người yêu trà", "Người muốn hiểu trà Việt", "Người mua trà làm quà", "Người quan tâm văn hóa trà", "Người tìm một khoảng chậm"],
        [],
        [
            T("vandinhtra.core.tea-region", "Tea & Region", "core",
                "Trà Việt, vùng trà, nguồn gốc, người làm trà và đất.",
                "Vân Đỉnh kể trà từ vùng và người, không từ bảng giá.",
                "Người muốn hiểu trà Việt",
                ["Vùng trà và người làm ra chén trà này."],
                ["Không catalogue sản phẩm."], 1),
            T("vandinhtra.core.flavor", "Flavor & Quality", "core",
                "Hương vị, chất lượng, cách nhận biết và cảm nhận trà.",
                "Cảm nhận hương trà là chuyện brand có lý do để kể.",
                "Người yêu trà",
                ["Cách nhận ra hương vị và chất của một loại trà Việt."],
                ["Không claim chữa bệnh."], 2),
            T("vandinhtra.core.ritual", "Tea Ritual", "core",
                "Pha trà, uống trà, không gian và ritual thưởng trà.",
                "Nghệ thuật thưởng trà là trung tâm, không phải đơn hàng.",
                "Người tìm khoảng chậm",
                ["Cách pha trà và cảm nhận hương trà.", "Những khoảng dừng nhỏ bên chén trà giúp con người sống chậm lại."],
                ["Không biến thành hướng dẫn bán hàng."], 3),
            T("vandinhtra.core.culture", "Tea Culture", "core",
                "Trà trong đời sống và văn hóa Việt.",
                "Văn hóa trà là câu chuyện brand.",
                "Người quan tâm văn hóa trà",
                ["Trà trong đời sống và văn hóa Việt."],
                ["Không lifestyle vô thưởng."], 4),
            T("vandinhtra.core.makers", "Tea Maker Stories", "core",
                "Con người phía sau trà.",
                "Người làm trà là một lý do để kể, không phải SKU.",
                "Người yêu trà",
                ["Câu chuyện người làm trà trên vùng chè."],
                ["Không hồ sơ nhân viên."], 5),
            T("vandinhtra.supporting.gifts", "Gifts", "supporting",
                "Quà biếu trà.", "Quà là cách trà đi vào đời sống.", "Người mua trà làm quà",
                ["Chọn trà làm quà vì câu chuyện vùng và hương."], ["Không chương trình giảm giá."], 10),
            T("vandinhtra.supporting.season", "Tea season", "supporting",
                "Mùa trà.", "Mùa hái là thời gian của vùng trà.", "Người yêu trà",
                ["Mùa trà năm nay trên vùng chè."], ["Không lịch khuyến mãi."], 11),
            T("vandinhtra.supporting.slow-life", "Slow life", "supporting",
                "Đời sống chậm bên trà.", "Khoảng chậm thuộc ritual trà.", "Người tìm khoảng chậm",
                ["Sống chậm hơn nhờ một chén trà."], ["Không self-help chung."], 12),
            T("vandinhtra.supporting.local-culture", "Local culture", "supporting",
                "Văn hóa địa phương quanh vùng trà.", "Khi nó nuôi câu chuyện trà.", "Người quan tâm văn hóa trà",
                ["Văn hóa quanh vùng chè Thái Nguyên."], ["Không du lịch đại trà."], 13),
            T("vandinhtra.supporting.experience", "Tea experience", "supporting",
                "Trải nghiệm trà.", "Trải nghiệm là cách cảm trà, không phải tour bán hàng.", "Người yêu trà",
                ["Một buổi thưởng trà và điều người ta nhận ra."], ["Không booking page."], 14),
            T("vandinhtra.adjacent.food", "Food", "adjacent",
                "Ẩm thực khi đi cùng trà.", "Phải còn là chuyện trà.", "Người yêu trà",
                ["Món ăn bên chén trà và cách trà đổi vị."], ["Không ẩm thực không có trà."], 20),
            T("vandinhtra.adjacent.travel", "Tea-region travel", "adjacent",
                "Đi tới vùng trà.", "Du lịch chỉ để hiểu đất và người làm trà.", "Người muốn hiểu trà Việt",
                ["Đi một vùng trà để gặp người làm trà."], ["Không guide du lịch chung."], 21),
            T("vandinhtra.adjacent.lifestyle", "Lifestyle", "adjacent",
                "Lifestyle có trà.", "Phải quay về trà, đất, người.", "Người tìm khoảng chậm",
                ["Nhịp sống chậm mà trung tâm vẫn là trà."], ["Không lifestyle không trà."], 22),
            T("vandinhtra.adjacent.vn-gifts", "Vietnamese gifts", "adjacent",
                "Quà tặng Việt khi là trà.", "Quà không trà thì không thuộc brand.", "Người mua quà",
                ["Quà Việt khi món quà là trà và câu chuyện vùng."], ["Không quà tặng chung."], 23),
            T("vandinhtra.off.pharmacy", "Pharmacy", "off-brand",
                "Nội dung dược phẩm, nhà thuốc.", "Trà không phải thuốc.", "—",
                ["Tư vấn thuốc và kho nhà thuốc."], ["Không."], 90),
            T("vandinhtra.off.disease", "Disease treatment", "off-brand",
                "Chữa bệnh bằng trà.", "Cấm claim trị bệnh.", "—",
                ["Trà chữa bệnh và giảm cân."], ["Không."], 91),
            T("vandinhtra.off.fefo", "FEFO", "off-brand",
                "FEFO và vận hành kho thuốc.", "Không phải chuyện trà.", "—",
                ["FEFO và hạn dùng thuốc."], ["Không."], 92),
            T("vandinhtra.off.it", "IT", "off-brand",
                "Nội dung IT.", "Vân Đỉnh không kể chuyện phần mềm.", "—",
                ["Xây hệ thống phần mềm và AI."], ["Không."], 93),
        ],
        ["Bán trà bằng câu chuyện về trà, đất, người và trải nghiệm — không biến thương hiệu thành catalogue sản phẩm."],
        "Một shop trà chỉ đăng giá và chương trình bán hàng.");

    private static BrandNarrativeDna XuanHoa() => new(
        1, "xuanhoa",
        "A real local pharmacy built on trust, responsible consultation and operational standards.",
        ["Người dân địa phương", "Gia đình", "Khách hàng của nhà thuốc", "Người cần được dược sĩ tư vấn đúng cách"],
        [],
        [
            T("xuanhoa.core.counter", "Counter Consultation", "core",
                "Những tình huống thực tế và cách tư vấn có trách nhiệm tại quầy.",
                "Giá trị Xuân Hòa bắt đầu từ lần tư vấn tử tế, không từ lời tự khen.",
                "Người dân cần dược sĩ tư vấn",
                ["Khách đến quầy cần được dược sĩ tư vấn đúng cách."],
                ["Không kê đơn thay bác sĩ. Không cam kết khỏi bệnh."], 1),
            T("xuanhoa.core.safety", "Medication Safety", "core",
                "Giúp khách hiểu cách dùng thuốc đúng và an toàn.",
                "An toàn khi dùng thuốc là chuyện nhà thuốc có trách nhiệm kể.",
                "Khách hàng nhà thuốc",
                ["Một vài thao tác nhỏ khi nhận thuốc có thể giúp tránh sai sót."],
                ["Không chẩn đoán. Không chữa khỏi."], 2),
            T("xuanhoa.core.standards", "Clean / Standard / Transparent Pharmacy", "core",
                "Kho, hạn dùng, bảo quản, quy trình nhà thuốc sạch và minh bạch.",
                "Chuẩn vận hành là một phần của sự tin cậy.",
                "Người dân địa phương",
                ["Kho sạch, hạn dùng rõ, quy trình minh bạch tại nhà thuốc."],
                ["Không thành bài bán phần mềm."], 3),
            T("xuanhoa.core.local-stories", "Local Customer Stories", "core",
                "Tình huống thật của khách địa phương.",
                "Nhà thuốc này thuộc về đời sống quanh quầy.",
                "Gia đình và khách địa phương",
                ["Một tình huống thật của khách quanh nhà thuốc."],
                ["Không case bệnh để hù."], 4),
            T("xuanhoa.core.pharmacist", "Pharmacist", "core",
                "Kiến thức, trách nhiệm và góc nhìn nghề dược sĩ.",
                "Người dược sĩ là người khách tin, không phải nhân vật quảng cáo.",
                "Người cần tư vấn",
                ["Dược sĩ giải thích trách nhiệm khi tư vấn tại quầy."],
                ["Đồng nghiệp học nghề không phải audience chính."], 5),
            T("xuanhoa.supporting.family-health", "Family health", "supporting",
                "Chăm sóc sức khỏe gia đình qua nhà thuốc.", "Khi còn là tư vấn có trách nhiệm.", "Gia đình",
                ["Gia đình hỏi dược sĩ trước khi dùng thuốc."], ["Không chữa bệnh tại nhà."], 10),
            T("xuanhoa.supporting.community", "Community health", "supporting",
                "Sức khỏe cộng đồng quanh nhà thuốc.", "Gắn với quầy và địa phương.", "Người dân địa phương",
                ["Nhà thuốc trong đời sống sức khỏe của phố."], ["Không chiến dịch y tế vĩ mô."], 11),
            T("xuanhoa.supporting.education", "Medication education", "supporting",
                "Giáo dục sử dụng thuốc.", "Giúp dùng đúng, không giúp tự chữa.", "Khách hàng",
                ["Cách đọc hạn dùng và hỏi dược sĩ trước khi dùng."], ["Không phác đồ điều trị."], 12),
            T("xuanhoa.supporting.local-life", "Local life", "supporting",
                "Đời sống địa phương quanh nhà thuốc.", "Chỉ khi còn liên quan quầy và sự tin cậy.", "Người dân địa phương",
                ["Đời sống phố và lần khách ghé quầy thuốc."], ["Không tin địa phương chung."], 13),
            T("xuanhoa.adjacent.habits", "Health habits", "adjacent",
                "Thói quen sức khỏe.", "Tránh biến thành chẩn đoán hoặc chữa bệnh.", "Khách hàng",
                ["Thói quen nào nên hỏi dược sĩ thay vì tự quyết."], ["Không lời khuyên điều trị."], 20),
            T("xuanhoa.adjacent.nutrition", "Nutrition", "adjacent",
                "Dinh dưỡng.", "Chỉ như thông tin cần dược sĩ đặt vào ngữ cảnh, không chữa bệnh.", "Gia đình",
                ["Dinh dưỡng và điều cần hỏi tại quầy, không phải đơn thuốc."], ["Không thực đơn chữa bệnh."], 21),
            T("xuanhoa.adjacent.prevention", "Prevention", "adjacent",
                "Phòng ngừa.", "Không vượt sang chẩn đoán.", "Người dân địa phương",
                ["Phòng ngừa bằng cách dùng thuốc đúng và hỏi người có trách nhiệm."], ["Không sàng lọc bệnh."], 22),
            T("xuanhoa.adjacent.family-life", "Family life", "adjacent",
                "Đời sống gia đình.", "Phải còn là chuyện thuốc và tư vấn, không thành Family OS.", "Gia đình",
                ["Gia đình giữ thuốc an toàn trong nhà."], ["Không FamilyOS. Không nuôi dạy con."], 23),
            T("xuanhoa.off.cure", "Cure claims", "off-brand",
                "Cam kết chữa khỏi.", "Nhà thuốc không hứa khỏi bệnh.", "—",
                ["Cam kết chữa khỏi sau vài ngày."], ["Không."], 90),
            T("xuanhoa.off.prescribing", "Prescribing instead of doctors", "off-brand",
                "Kê đơn thay bác sĩ.", "Tư vấn không phải kê đơn.", "—",
                ["Kê đơn thay bác sĩ qua bài viết."], ["Không."], 91),
            T("xuanhoa.off.politics", "Politics", "off-brand",
                "Chính trị.", "Ngoài quầy thuốc.", "—",
                ["Bình luận chính trị."], ["Không."], 92),
            T("xuanhoa.off.it", "IT", "off-brand",
                "Nội dung IT và phần mềm.", "Xuân Hòa không phải kênh công nghệ.", "—",
                ["Xây platform và AI cho doanh nghiệp."], ["Không."], 93),
            T("xuanhoa.off.familyos", "FamilyOS", "off-brand",
                "FamilyOS và nuôi dạy con.", "Không lấy chuyện Famixa làm chuyện nhà thuốc.", "—",
                ["FamilyOS giúp cha mẹ nuôi dạy con."], ["Không."], 94),
            T("xuanhoa.off.selling", "Excessive selling", "off-brand",
                "Bán hàng quá mức, kênh bán thuốc online.", "Tin cậy không đến từ thúc mua.", "—",
                ["Mua thuốc online giá tốt nhất hôm nay."], ["Không thành shop thuốc online."], 95),
        ],
        ["Giá trị đến từ sự tin cậy, không phải từ việc nói mình tốt. Peer pharmacist không phải audience chính."],
        "Một kênh bán thuốc online.");

    private static BrandNarrativeDna ThaiNguyenLife() => new(
        1, "tnlife",
        "A local life platform helping people in Thái Nguyên know what is happening, what they need, where to go and whom to contact.",
        ["Người đang sống tại Thái Nguyên", "Sinh viên", "Người mới đến", "Người tìm việc", "Doanh nghiệp và người đăng thông tin địa phương"],
        [],
        [
            T("tnlife.core.jobs", "Jobs", "core",
                "Việc thật tại Thái Nguyên, thông tin rõ, kết nối trực tiếp.",
                "Việc làm địa phương là một lý do người ở đây mở Thái Nguyên Life.",
                "Người tìm việc và sinh viên",
                ["Việc làm đang cần người ở Thái Nguyên."],
                ["Không bịa lương. Không cam kết có việc."], 1),
            T("tnlife.core.events", "Events", "core",
                "Hôm nay và cuối tuần có gì ở Thái Nguyên.",
                "Sự kiện giúp người sống ở đây biết hôm nay có gì.",
                "Người đang sống tại Thái Nguyên",
                ["Hôm nay ở Thái Nguyên có sự kiện gì."],
                ["Không lịch cả nước."], 2),
            T("tnlife.core.experience", "Ăn – chơi – trải nghiệm", "core",
                "Những nơi đáng đi và đáng biết tại Thái Nguyên.",
                "Ăn chơi trải nghiệm trả lời câu đi đâu cho người đang ở thành phố.",
                "Người mới đến và người sống tại Thái Nguyên",
                ["Cuối tuần này ở Thái Nguyên có gì để đi và trải nghiệm?"],
                ["Phải là Thái Nguyên, không phải gợi ý du lịch chung."], 3),
            T("tnlife.core.housing", "Housing / rooms", "core",
                "Nhà ở và phòng cho người đang sống hoặc mới đến Thái Nguyên.",
                "Chỗ ở là nhu cầu của người ở thành phố này.",
                "Người mới đến",
                ["Phòng và nhà ở cho người đang ở Thái Nguyên."],
                ["Không rao phòng cả nước."], 4),
            T("tnlife.core.local-life", "Đời sống địa phương", "core",
                "Những điều đang diễn ra trong thành phố Thái Nguyên.",
                "Đời sống địa phương là câu chuyện brand có lý do để kể.",
                "Người đang sống tại Thái Nguyên",
                ["Những địa điểm nhỏ mà người mới đến Thái Nguyên nên biết."],
                ["Không tin tức quốc gia."], 5),
            T("tnlife.supporting.businesses", "Local businesses", "supporting",
                "Doanh nghiệp địa phương.", "Khi hữu ích cho người ở Thái Nguyên.", "Doanh nghiệp địa phương",
                ["Một quán hay dịch vụ trong thành phố người dân dùng được."], ["Không hồ sơ công ty quốc gia."], 10),
            T("tnlife.supporting.services", "Local services", "supporting",
                "Dịch vụ địa phương.", "Người ở đây cần tìm ai.", "Người cần dịch vụ",
                ["Dịch vụ trong Thái Nguyên và cách liên hệ."], ["Không marketplace cả nước."], 11),
            T("tnlife.supporting.community", "Community", "supporting",
                "Cộng đồng Thái Nguyên.", "Cộng đồng của thành phố này.", "Người đang sống tại đây",
                ["Sinh hoạt cộng đồng trong Thái Nguyên."], ["Không cộng đồng ảo chung."], 12),
            T("tnlife.supporting.newcomers", "Newcomers", "supporting",
                "Người mới đến Thái Nguyên.", "Họ cần biết hôm nay có gì, đi đâu, tìm ai.", "Người mới đến",
                ["Người mới đến Thái Nguyên cần biết gì trước."], ["Không cẩm nang nhập cư chung."], 13),
            T("tnlife.adjacent.culture", "Culture", "adjacent",
                "Văn hóa Thái Nguyên.", "Phải hữu ích hoặc gắn đời sống người đang ở đây.", "Người sống tại Thái Nguyên",
                ["Văn hóa Thái Nguyên mà người sống ở đây chạm được."], ["Không chuyên đề văn hóa không nơi chốn."], 20),
            T("tnlife.adjacent.tourism", "Tourism", "adjacent",
                "Du lịch khi là đi trong Thái Nguyên.", "Vẫn phải trả lời đi đâu cho người ở đây hoặc người đến thành phố.", "Người mới đến",
                ["Điểm trong Thái Nguyên đáng ghé cuối tuần."], ["Không du lịch Việt Nam chung."], 21),
            T("tnlife.adjacent.history", "History", "adjacent",
                "Lịch sử Thái Nguyên.", "Khi giúp người ở đây hiểu thành phố.", "Người sống tại Thái Nguyên",
                ["Một mảnh lịch sử Thái Nguyên còn thấy trong thành phố."], ["Không sử Việt Nam chung."], 22),
            T("tnlife.adjacent.people", "Local people", "adjacent",
                "Con người địa phương.", "Người thật đang sống hoặc làm việc ở Thái Nguyên.", "Cộng đồng",
                ["Người đang làm một việc hữu ích trong Thái Nguyên."], ["Không chân dung người nổi tiếng cả nước."], 23),
            T("tnlife.off.pharmacy", "Pharmacy", "off-brand",
                "Nội dung nhà thuốc.", "Thái Nguyên Life không kể chuyện quầy thuốc.", "—",
                ["Tư vấn thuốc và FEFO nhà thuốc."], ["Không."], 90),
            T("tnlife.off.familyos", "FamilyOS", "off-brand",
                "FamilyOS.", "Không lấy chuyện nuôi dạy con của Famixa.", "—",
                ["FamilyOS và cách nuôi dạy một đứa trẻ."], ["Không."], 91),
            T("tnlife.off.novixa", "Novixa", "off-brand",
                "Nội dung Novixa và vận hành nhà thuốc.", "Không phải đời sống thành phố.", "—",
                ["Vận hành kho nhà thuốc và Pharmacy Health Check."], ["Không."], 92),
            T("tnlife.off.kit-it", "KIT IT content", "off-brand",
                "Nội dung IT của KIT.", "Không phải chuyện người dân Thái Nguyên hôm nay.", "—",
                ["Xây platform phần mềm và AI cho doanh nghiệp."], ["Không."], 93),
            T("tnlife.off.national-news", "National news", "off-brand",
                "Tin tức cả nước không có liên hệ Thái Nguyên.", "Brand không phải báo cả nước.", "—",
                ["Tin tức cả nước hôm nay không nhắc Thái Nguyên."], ["Không."], 94),
        ],
        ["Mọi nội dung phải trả lời được: điều này có ích gì cho người đang sống ở Thái Nguyên?"],
        "Một website tin tức tổng hợp cả nước.");
}
