-- KitPlatform 139: SPA_HEALTH_V1 seed — 35 questions, 8 scored index groups
-- Depends on: 068_assessment_engine.sql
-- Generated by scripts/gen-spa-health-v1-seed.py
-- Safe for live pharmacy: new UUID namespace a0000002-*, never updates PHARMACY_V1

INSERT INTO assessment_template (id, code, name, version, description, verticals, status)
VALUES (
    'a0000002-0000-4000-8000-000000000001',
    'SPA_HEALTH_V1',
    'SPA Health Check — Đánh giá sức khỏe doanh nghiệp Spa',
    '1.0',
    'Bộ 35 câu — 8 chỉ số + Business Health Score. Vertical spa_health.',
    ARRAY['spa_health'],
    'active'
)
ON CONFLICT (code, version) DO NOTHING;

INSERT INTO assessment_category (id, template_id, code, name, sort_order, weight)
VALUES
    ('a0000002-0000-4000-8000-000000000011', 'a0000002-0000-4000-8000-000000000001', 'CONTEXT', 'Doanh nghiệp (bối cảnh)', 1, 0),
    ('a0000002-0000-4000-8000-000000000012', 'a0000002-0000-4000-8000-000000000001', 'MKT', 'Khách hàng & Marketing', 2, 18),
    ('a0000002-0000-4000-8000-000000000013', 'a0000002-0000-4000-8000-000000000001', 'LOY', 'Trung thành khách hàng', 3, 14),
    ('a0000002-0000-4000-8000-000000000014', 'a0000002-0000-4000-8000-000000000001', 'SAL', 'Tư vấn & Bán hàng', 4, 14),
    ('a0000002-0000-4000-8000-000000000015', 'a0000002-0000-4000-8000-000000000001', 'TRT', 'Lịch hẹn & Liệu trình', 5, 14),
    ('a0000002-0000-4000-8000-000000000016', 'a0000002-0000-4000-8000-000000000001', 'HR', 'Nhân sự', 6, 10),
    ('a0000002-0000-4000-8000-000000000017', 'a0000002-0000-4000-8000-000000000001', 'FIN', 'Tài chính', 7, 10),
    ('a0000002-0000-4000-8000-000000000018', 'a0000002-0000-4000-8000-000000000001', 'OPS', 'Vận hành', 8, 10),
    ('a0000002-0000-4000-8000-000000000019', 'a0000002-0000-4000-8000-000000000001', 'DIG', 'Chuyển đổi số', 9, 10)
ON CONFLICT (template_id, code) DO NOTHING;

INSERT INTO assessment_dimension (id, category_id, code, name, sort_order, weight)
VALUES
    ('a0000002-0000-4000-8000-000000000021', 'a0000002-0000-4000-8000-000000000011', 'CONTEXT_OVERALL', 'Doanh nghiệp (bối cảnh) (tổng)', 1, 1),
    ('a0000002-0000-4000-8000-000000000022', 'a0000002-0000-4000-8000-000000000012', 'MKT_OVERALL', 'Khách hàng & Marketing (tổng)', 1, 1),
    ('a0000002-0000-4000-8000-000000000023', 'a0000002-0000-4000-8000-000000000013', 'LOY_OVERALL', 'Trung thành khách hàng (tổng)', 1, 1),
    ('a0000002-0000-4000-8000-000000000024', 'a0000002-0000-4000-8000-000000000014', 'SAL_OVERALL', 'Tư vấn & Bán hàng (tổng)', 1, 1),
    ('a0000002-0000-4000-8000-000000000025', 'a0000002-0000-4000-8000-000000000015', 'TRT_OVERALL', 'Lịch hẹn & Liệu trình (tổng)', 1, 1),
    ('a0000002-0000-4000-8000-000000000026', 'a0000002-0000-4000-8000-000000000016', 'HR_OVERALL', 'Nhân sự (tổng)', 1, 1),
    ('a0000002-0000-4000-8000-000000000027', 'a0000002-0000-4000-8000-000000000017', 'FIN_OVERALL', 'Tài chính (tổng)', 1, 1),
    ('a0000002-0000-4000-8000-000000000028', 'a0000002-0000-4000-8000-000000000018', 'OPS_OVERALL', 'Vận hành (tổng)', 1, 1),
    ('a0000002-0000-4000-8000-000000000029', 'a0000002-0000-4000-8000-000000000019', 'DIG_OVERALL', 'Chuyển đổi số (tổng)', 1, 1)
ON CONFLICT (category_id, code) DO NOTHING;

INSERT INTO assessment_question (id, dimension_id, code, title, question_type, scorable, required, sort_order, weight, metadata)
VALUES
    ('a0000002-0000-4000-8000-000000000101', 'a0000002-0000-4000-8000-000000000021', 'S1', 'Spa của bạn thuộc mô hình nào?', 'single_choice', FALSE, TRUE, 1, 0, '{}'),
    ('a0000002-0000-4000-8000-000000000102', 'a0000002-0000-4000-8000-000000000021', 'S2', 'Spa hoạt động bao lâu?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000103', 'a0000002-0000-4000-8000-000000000021', 'S3', 'Số nhân sự?', 'single_choice', TRUE, TRUE, 3, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000104', 'a0000002-0000-4000-8000-000000000021', 'S4', 'Lượt khách trung bình / ngày?', 'single_choice', TRUE, TRUE, 4, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000105', 'a0000002-0000-4000-8000-000000000021', 'S5', 'Doanh thu trung bình / tháng?', 'single_choice', TRUE, TRUE, 5, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000106', 'a0000002-0000-4000-8000-000000000021', 'S6', 'Khách hàng mới chủ yếu đến từ đâu?', 'single_choice', FALSE, TRUE, 6, 0, '{}'),
    ('a0000002-0000-4000-8000-000000000107', 'a0000002-0000-4000-8000-000000000022', 'S7', 'Bạn có biết chi phí để có một khách hàng mới (CAC)?', 'single_choice', TRUE, TRUE, 1, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000108', 'a0000002-0000-4000-8000-000000000023', 'S8', 'Tỷ lệ khách quay lại sau lần đầu?', 'single_choice', TRUE, TRUE, 1, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000109', 'a0000002-0000-4000-8000-000000000023', 'S9', 'Spa có CRM / lưu lịch sử khách hàng?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000110', 'a0000002-0000-4000-8000-000000000022', 'S10', 'Spa có chương trình thành viên và gửi ưu đãi định kỳ?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000111', 'a0000002-0000-4000-8000-000000000024', 'S11', 'Spa có quy trình tư vấn chuẩn?', 'single_choice', TRUE, TRUE, 1, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000112', 'a0000002-0000-4000-8000-000000000024', 'S12', 'Có lưu hồ sơ tư vấn khách hàng?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000113', 'a0000002-0000-4000-8000-000000000024', 'S13', 'Có theo dõi tỷ lệ chốt dịch vụ sau tư vấn?', 'single_choice', TRUE, TRUE, 3, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000114', 'a0000002-0000-4000-8000-000000000024', 'S14', 'Có bán thêm dịch vụ (upsell) hoặc gói liệu trình?', 'single_choice', TRUE, TRUE, 4, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000115', 'a0000002-0000-4000-8000-000000000025', 'S15', 'Lịch hẹn đang quản lý bằng gì?', 'single_choice', TRUE, TRUE, 1, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000116', 'a0000002-0000-4000-8000-000000000025', 'S16', 'Mức độ kiểm soát trùng lịch?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000117', 'a0000002-0000-4000-8000-000000000025', 'S17', 'Có nhắc lịch cho khách?', 'single_choice', TRUE, TRUE, 3, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000118', 'a0000002-0000-4000-8000-000000000025', 'S18', 'Có quản lý số buổi liệu trình còn lại?', 'single_choice', TRUE, TRUE, 4, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000119', 'a0000002-0000-4000-8000-000000000025', 'S19', 'Có cảnh báo khi khách bỏ dở / ngưng liệu trình?', 'single_choice', TRUE, TRUE, 5, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000120', 'a0000002-0000-4000-8000-000000000026', 'S20', 'Có KPI cho nhân viên / kỹ thuật viên?', 'single_choice', TRUE, TRUE, 1, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000121', 'a0000002-0000-4000-8000-000000000026', 'S21', 'Hoa hồng / thưởng doanh số được tính thế nào?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000122', 'a0000002-0000-4000-8000-000000000026', 'S22', 'Có theo dõi doanh thu theo từng kỹ thuật viên?', 'single_choice', TRUE, TRUE, 3, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000123', 'a0000002-0000-4000-8000-000000000026', 'S23', 'Có đánh giá chất lượng phục vụ của nhân viên?', 'single_choice', TRUE, TRUE, 4, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000124', 'a0000002-0000-4000-8000-000000000027', 'S24', 'Có dashboard / báo cáo doanh thu định kỳ?', 'single_choice', TRUE, TRUE, 1, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000125', 'a0000002-0000-4000-8000-000000000027', 'S25', 'Bạn có biết dịch vụ nào lợi nhuận cao nhất?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000126', 'a0000002-0000-4000-8000-000000000027', 'S26', 'Có theo dõi công nợ khách / đối tác?', 'single_choice', TRUE, TRUE, 3, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000127', 'a0000002-0000-4000-8000-000000000027', 'S27', 'Có theo dõi doanh thu theo nguồn khách?', 'single_choice', TRUE, TRUE, 4, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000128', 'a0000002-0000-4000-8000-000000000028', 'S28', 'Có SOP (quy trình chuẩn) cho các dịch vụ chính?', 'single_choice', TRUE, TRUE, 1, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000129', 'a0000002-0000-4000-8000-000000000028', 'S29', 'Có kiểm soát tồn kho mỹ phẩm / vật tư?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000130', 'a0000002-0000-4000-8000-000000000028', 'S30', 'Có theo dõi hạn sử dụng mỹ phẩm / vật tư?', 'single_choice', TRUE, TRUE, 3, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000131', 'a0000002-0000-4000-8000-000000000028', 'S31', 'Có đo mức độ hài lòng khách hàng sau dịch vụ?', 'single_choice', TRUE, TRUE, 4, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000132', 'a0000002-0000-4000-8000-000000000029', 'S32', 'Spa đang dùng phần mềm quản lý ở mức nào?', 'single_choice', TRUE, TRUE, 1, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000133', 'a0000002-0000-4000-8000-000000000029', 'S33', 'Khách có thể đặt lịch online hoặc qua app?', 'single_choice', TRUE, TRUE, 2, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000134', 'a0000002-0000-4000-8000-000000000029', 'S34', 'Mức độ số hóa nâng cao (dashboard realtime / AI CSKH)?', 'single_choice', TRUE, TRUE, 3, 1, '{}'),
    ('a0000002-0000-4000-8000-000000000135', 'a0000002-0000-4000-8000-000000000029', 'S35', 'Vấn đề lớn nhất cần giải quyết trong 12 tháng tới?', 'single_choice', FALSE, TRUE, 4, 0, '{"leadTag":"priority_need"}')
ON CONFLICT (dimension_id, code) DO NOTHING;

-- Options S1
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('skin', 'Spa chăm sóc da', NULL::smallint, 1),
    ('therapy', 'Spa trị liệu', NULL::smallint, 2),
    ('clinic', 'Clinic thẩm mỹ', NULL::smallint, 3),
    ('beauty', 'Thẩm mỹ viện', NULL::smallint, 4),
    ('chain', 'Chuỗi Spa', NULL::smallint, 5)
) AS v(code, label, score, ord)
WHERE q.code = 'S1' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S2
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Dưới 1 năm', 1::smallint, 1),
    ('OPT2', '1-3 năm', 2::smallint, 2),
    ('OPT3', '3-5 năm', 3::smallint, 3),
    ('OPT4', 'Trên 5 năm', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S2' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S3
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', '1-3 người', 1::smallint, 1),
    ('OPT2', '4-10 người', 2::smallint, 2),
    ('OPT3', '11-20 người', 3::smallint, 3),
    ('OPT4', 'Trên 20 người', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S3' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S4
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Dưới 10', 1::smallint, 1),
    ('OPT2', '10-20', 2::smallint, 2),
    ('OPT3', '21-40', 3::smallint, 3),
    ('OPT4', 'Trên 40', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S4' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S5
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Dưới 50 triệu', 1::smallint, 1),
    ('OPT2', '50-150 triệu', 2::smallint, 2),
    ('OPT3', '150-400 triệu', 3::smallint, 3),
    ('OPT4', 'Trên 400 triệu', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S5' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S6
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('facebook', 'Facebook', NULL::smallint, 1),
    ('tiktok', 'TikTok', NULL::smallint, 2),
    ('google', 'Google', NULL::smallint, 3),
    ('referral', 'Giới thiệu khách', NULL::smallint, 4),
    ('walkin', 'Đi ngang / gần cửa', NULL::smallint, 5),
    ('other', 'Khác', NULL::smallint, 6)
) AS v(code, label, score, ord)
WHERE q.code = 'S6' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S7
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Không biết', 1::smallint, 1),
    ('OPT2', 'Ước lượng / cảm tính', 2::smallint, 2),
    ('OPT3', 'Có số liệu rõ ràng', 3::smallint, 3)
) AS v(code, label, score, ord)
WHERE q.code = 'S7' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S8
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Dưới 20%', 1::smallint, 1),
    ('OPT2', '20-40%', 2::smallint, 2),
    ('OPT3', '40-60%', 3::smallint, 3),
    ('OPT4', 'Trên 60%', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S8' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S15
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Facebook / Zalo / tin nhắn', 1::smallint, 1),
    ('OPT2', 'Sổ giấy', 2::smallint, 2),
    ('OPT3', 'Excel / Google Sheet', 3::smallint, 3),
    ('OPT4', 'Phần mềm / lịch chuyên dụng', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S15' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S16
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Thường xuyên bị trùng / sót', 1::smallint, 1),
    ('OPT2', 'Thỉnh thoảng xảy ra', 2::smallint, 2),
    ('OPT3', 'Hiếm, xử lý được nhanh', 3::smallint, 3),
    ('OPT4', 'Hệ thống chặn / gần như không trùng', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S16' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S21
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Không có hoa hồng', 1::smallint, 1),
    ('OPT2', 'Có nhưng tính tay, thiếu minh bạch', 2::smallint, 2),
    ('OPT3', 'Có quy tắc rõ, tính tay theo kỳ', 3::smallint, 3),
    ('OPT4', 'Tính tự động trên hệ thống', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S21' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S25
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Không biết', 1::smallint, 1),
    ('OPT2', 'Ước lượng theo cảm tính', 2::smallint, 2),
    ('OPT3', 'Có số liệu lãi/gộp theo dịch vụ', 3::smallint, 3)
) AS v(code, label, score, ord)
WHERE q.code = 'S25' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S32
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Chưa dùng phần mềm quản lý', 1::smallint, 1),
    ('OPT2', 'Chỉ Excel / lịch Google / Zalo', 2::smallint, 2),
    ('OPT3', 'Có phần mềm, dùng một phần tính năng', 3::smallint, 3),
    ('OPT4', 'Phần mềm là xương sống vận hành hàng ngày', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S32' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S33
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Chỉ đặt qua gọi / nhắn tay', 1::smallint, 1),
    ('OPT2', 'Đặt qua Facebook/Zalo, nhân viên nhập lịch', 2::smallint, 2),
    ('OPT3', 'Có link / form đặt lịch', 3::smallint, 3),
    ('OPT4', 'App / cổng đặt lịch + xác nhận tự động', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S33' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S34
INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, v.code, v.label, v.score, v.ord
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('OPT1', 'Chưa có', 1::smallint, 1),
    ('OPT2', 'Chỉ báo cáo tĩnh cuối kỳ', 2::smallint, 2),
    ('OPT3', 'Có dashboard gần realtime hoặc chatbot/AI CSKH cơ bản', 3::smallint, 3),
    ('OPT4', 'Có dashboard realtime và AI/chatbot hỗ trợ chăm sóc', 4::smallint, 4)
) AS v(code, label, score, ord)
WHERE q.code = 'S34' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

-- Options S35
INSERT INTO assessment_option (question_id, code, label, score, sort_order, metadata)
SELECT q.id, v.code, v.label, NULL::smallint, v.ord, v.meta::jsonb
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
CROSS JOIN (VALUES
    ('new_customers', 'Có thêm khách hàng mới', 1, '{"tag":"priority_new_customers"}'),
    ('retention', 'Tăng tỷ lệ khách quay lại', 2, '{"tag":"priority_retention"}'),
    ('revenue_per_guest', 'Tăng doanh thu trên mỗi khách', 3, '{"tag":"priority_revenue_per_guest"}'),
    ('booking', 'Quản lý lịch hẹn', 4, '{"tag":"priority_booking"}'),
    ('treatment', 'Quản lý liệu trình', 5, '{"tag":"priority_treatment"}'),
    ('staff_perf', 'Nâng cao hiệu suất nhân viên', 6, '{"tag":"priority_staff"}'),
    ('cost', 'Quản lý chi phí', 7, '{"tag":"priority_cost"}'),
    ('digital', 'Chuyển đổi số', 8, '{"tag":"priority_digital"}'),
    ('other', 'Khác', 9, '{"tag":"priority_other"}')
) AS v(code, label, ord, meta)
WHERE q.code = 'S35' AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
ON CONFLICT (question_id, code) DO NOTHING;

INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, 'OPT1', 'Không có', 1, 1
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
WHERE q.scorable = TRUE AND q.code NOT IN ('S1','S15','S16','S2','S21','S25','S3','S32','S33','S34','S35','S4','S5','S6','S7','S8')
  AND NOT EXISTS (SELECT 1 FROM assessment_option o WHERE o.question_id = q.id AND o.code = 'OPT1');

INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, 'OPT2', 'Có nhưng thủ công / không ổn định', 2, 2
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
WHERE q.scorable = TRUE AND q.code NOT IN ('S1','S15','S16','S2','S21','S25','S3','S32','S33','S34','S35','S4','S5','S6','S7','S8')
  AND NOT EXISTS (SELECT 1 FROM assessment_option o WHERE o.question_id = q.id AND o.code = 'OPT2');

INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, 'OPT3', 'Có quy trình, theo dõi một phần', 3, 3
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
WHERE q.scorable = TRUE AND q.code NOT IN ('S1','S15','S16','S2','S21','S25','S3','S32','S33','S34','S35','S4','S5','S6','S7','S8')
  AND NOT EXISTS (SELECT 1 FROM assessment_option o WHERE o.question_id = q.id AND o.code = 'OPT3');

INSERT INTO assessment_option (question_id, code, label, score, sort_order)
SELECT q.id, 'OPT4', 'Đầy đủ, đo lường hoặc tự động', 4, 4
FROM assessment_question q
JOIN assessment_dimension d ON d.id = q.dimension_id
JOIN assessment_category c ON c.id = d.category_id AND c.template_id = 'a0000002-0000-4000-8000-000000000001'
WHERE q.scorable = TRUE AND q.code NOT IN ('S1','S15','S16','S2','S21','S25','S3','S32','S33','S34','S35','S4','S5','S6','S7','S8')
  AND NOT EXISTS (SELECT 1 FROM assessment_option o WHERE o.question_id = q.id AND o.code = 'OPT4');

INSERT INTO assessment_rule (id, template_id, code, name, expression, action_type, action_payload, priority)
VALUES
    (
        'a0000002-0000-4000-8000-000000000701',
        'a0000002-0000-4000-8000-000000000001',
        'INSIGHT_LOY_LOW',
        'Điểm trung thành thấp',
        'category.LOY.score < 2.5',
        'insight',
        '{"title":"Cơ hội giữ chân khách","body":"Tỷ lệ quay lại và CRM còn yếu. Cần tập trung loyalty và chăm sóc sau dịch vụ.","severity":"warning","scopeType":"category","scopeCode":"LOY"}'::jsonb,
        80
    ),
    (
        'a0000002-0000-4000-8000-000000000702',
        'a0000002-0000-4000-8000-000000000001',
        'INSIGHT_DIG_LOW',
        'Số hóa thấp',
        'category.DIG.score < 2.5',
        'insight',
        '{"title":"Cần chuyển đổi số","body":"Lịch hẹn, liệu trình và chăm sóc khách nên được số hóa để giảm sót và tăng trải nghiệm.","severity":"info","scopeType":"category","scopeCode":"DIG"}'::jsonb,
        70
    )
ON CONFLICT (template_id, code) DO NOTHING;
