using System.Text.Json;
using KitPlatform.Packs.Sales;

namespace KitPlatform.Packs.Sales.Infrastructure;

/// <summary>
/// Novixa Pain Library V1 — Adaptive Pain Discovery.
/// Hooks ask; solution stays off-stage until the pharmacy confirms the pain.
/// </summary>
internal static class NovixaPainCatalog
{
    public const int Version = 1;

    public static readonly IReadOnlyDictionary<string, string> CategoryLabels = new Dictionary<string, string>
    {
        ["owner"] = "Chủ phụ thuộc",
        ["staff"] = "Nhân viên",
        ["inventory"] = "Kho",
        ["customer"] = "Khách hàng",
        ["revenue"] = "Doanh thu",
        ["data"] = "Dữ liệu / quản trị",
        ["growth"] = "Mở rộng",
        ["tech"] = "Công nghệ",
    };

    /// <summary>Explore mix for new leads (sums to 1.00).</summary>
    public static readonly IReadOnlyDictionary<string, decimal> ExploreShare = new Dictionary<string, decimal>
    {
        ["staff"] = 0.20m,
        ["owner"] = 0.15m,
        ["inventory"] = 0.15m,
        ["customer"] = 0.15m,
        ["revenue"] = 0.10m,
        ["data"] = 0.10m,
        ["growth"] = 0.10m,
        ["tech"] = 0.05m,
    };

    public static readonly IReadOnlyDictionary<string, string> Aliases = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["after_sale"] = "PAIN-CUST-002",
        ["near_expiry"] = "PAIN-INV-004",
        ["away_blind"] = "PAIN-OWN-002",
        ["shift_handoff"] = "PAIN-OWN-004",
        ["owner_counter"] = "PAIN-OWN-001",
        ["staff_turnover"] = "PAIN-STAFF-004",
        ["reporting"] = "PAIN-DATA-003",
    };

    public static IReadOnlyList<NovixaPainDef> All { get; } = Build();

    public static string Canonical(string? code)
    {
        var raw = (code ?? "").Trim();
        if (string.IsNullOrWhiteSpace(raw))
            return All[0].Code;
        if (Aliases.TryGetValue(raw, out var mapped))
            return mapped;
        return All.Any(p => p.Code == raw) ? raw : All[0].Code;
    }

    public static NovixaPainDef Get(string? code) =>
        All.FirstOrDefault(p => p.Code == Canonical(code)) ?? All[0];

    public static string CategoryLabel(string category) =>
        CategoryLabels.TryGetValue(category, out var label) ? label : category;

    public static KitSalesPainDto ToDto(NovixaPainDef p) => new(
        p.Code,
        p.Category,
        CategoryLabel(p.Category),
        p.Name,
        p.Description,
        p.Symptoms,
        p.Signals,
        p.Hook,
        p.Outreach,
        p.Question,
        p.SolutionDirection,
        p.SolutionMapping,
        p.Cta,
        p.Objections,
        p.PhcMapping);

    public static string CatalogJson(NovixaPainDef p) => JsonSerializer.Serialize(new
    {
        p.Symptoms,
        p.Signals,
        p.Hook,
        p.Outreach,
        p.Question,
        p.SolutionDirection,
        p.SolutionMapping,
        p.Cta,
        p.Objections,
        p.PhcMapping,
        p.Aliases,
    });

    private static IReadOnlyList<NovixaPainDef> Build() =>
    [
        P("PAIN-OWN-001", "owner", "Chủ phải có mặt cả ngày",
            "Nhà thuốc chỉ yên khi chủ đứng đó.",
            ["Chủ đứng quầy gần như cả ngày", "Ít khi giao ca cho nhân viên tự quyết"],
            ["Chủ hay đăng bài từ quầy", "Khó hẹn gặp ngoài giờ mở cửa"],
            "Nhà thuốc mình có ngày nào chủ không cần có mặt mà vẫn yên tâm không?",
            "Nhiều nhà thuốc mình gặp vận hành ổn khi chủ đứng đó — nhưng một ngày chủ bận việc riêng là cả quầy hơi chao.",
            "Anh/chị có phải có mặt gần như cả ngày mới yên không?",
            "Chuẩn hóa việc hàng ngày + nhìn được quầy khi không đứng đó.",
            "Dashboard từ xa + quy trình ca + dữ liệu thay vì chỉ kinh nghiệm chủ",
            "Nhà thuốc mình có gặp tình trạng này không?",
            ["Nhân viên cũng làm được", "Quán nhỏ nên chủ thích đứng"],
            "phc.ops_owner",
            ["owner_counter"]),
        P("PAIN-OWN-002", "owner", "Đi vắng là không yên tâm",
            "Chủ ra ngoài là không nắm được quầy đang thế nào.",
            ["Phải gọi về hỏi", "Xem camera nhưng không biết số"],
            ["Chủ hay nhắn nhân viên khi vắng"],
            "Lúc anh/chị đi vắng, nhà thuốc có nắm được không hay phải gọi về hỏi?",
            "Nhiều chủ kể: ra ngoài vài tiếng là phải hỏi nhân viên bán gì, còn hàng gì, có việc gì phát sinh.",
            "Khi anh/chị không có mặt, phần nào khiến mình ít yên nhất?",
            "Nhìn được bán / tồn / việc phát sinh mà không cần gọi hỏi.",
            "Remote visibility + cảnh báo bất thường",
            "Lúc đi vắng anh/chị thường phải hỏi nhân viên điều gì?",
            ["Có camera rồi", "Nhân viên tin được"],
            "phc.ops_away",
            ["away_blind"]),
        P("PAIN-OWN-003", "owner", "Nhân viên gặp việc lại gọi chủ",
            "Mọi quyết định nhỏ vẫn chảy về chủ.",
            ["Điện thoại chủ reo khi đang bận", "Nhân viên không dám quyết giá / đổi trả"],
            ["Chủ than bị gọi cả ngày"],
            "Nhân viên gặp việc hơi lệch một chút là gọi anh/chị chứ?",
            "Mình gặp nhiều nhà thuốc nhân viên không phải không giỏi — mà chưa có khung để tự xử, nên việc gì cũng hỏi chủ.",
            "Trong ngày anh/chị bị gọi về quầy khoảng mấy lần?",
            "Khung xử lý thường gặp + dữ liệu để nhân viên tự quyết trong giới hạn.",
            "Quy trình chuẩn + trợ giúp tại quầy",
            "Việc nào nhân viên hay gọi anh/chị nhất?",
            ["Gọi cho chắc", "Quán nhỏ nên hỏi cũng nhanh"],
            "phc.ops_owner",
            []),
        P("PAIN-OWN-004", "owner", "Chủ phải kiểm tra từng việc",
            "Không kiểm thì không biết ca vừa rồi ra sao.",
            ["Chủ đối tiền / tồn cuối ngày", "Giao ca vẫn lệch"],
            ["Cuối ngày chủ ở lại lâu"],
            "Cuối ngày anh/chị có phải tự kiểm từng việc mới yên không?",
            "Nhiều nhà thuốc giao ca xong chủ vẫn phải xem lại bán, tồn, tiền — vì chưa tin số đang khớp.",
            "Phần nào anh/chị hay phải tự kiểm nhất: tiền, tồn, hay việc giao ca?",
            "Số khớp theo ca, chủ xem điểm lệch thay vì soi từng việc.",
            "Đối soát ca + tồn + tiền",
            "Giao ca nhà thuốc mình đang lệch chỗ nào nhiều nhất?",
            ["Thói quen", "Nhân viên mới nên phải soi"],
            "phc.ops_shift",
            ["shift_handoff"]),
        P("PAIN-OWN-005", "owner", "Vận hành dựa vào kinh nghiệm chủ",
            "Cách làm nằm trong đầu chủ, khó truyền.",
            ["Mỗi việc chủ chỉ miệng", "Vắng chủ là làm khác"],
            ["Chủ nói “làm như mình hay làm”"],
            "Việc nhà thuốc mình đang chạy nhiều nhất vẫn nằm trong đầu anh/chị chứ?",
            "Mình thấy nhà thuốc nào cũng có “cách của chủ”. Hay — nhưng khi chủ không đứng đó, cách đó không đi theo nhân viên.",
            "Anh/chị có việc nào chỉ mình làm được, giao người khác là không giống?",
            "Đưa kinh nghiệm chủ thành việc lặp lại được.",
            "Chuẩn hóa quy trình + dữ liệu thay trí nhớ",
            "Việc nào anh/chị thấy khó giao nhất?",
            ["Kinh nghiệm mới đúng", "Nhà thuốc nhỏ không cần viết ra"],
            "phc.ops_owner",
            []),
        P("PAIN-OWN-006", "owner", "Khó giao quyền cho nhân viên",
            "Muốn tin nhân viên nhưng chưa có chỗ dựa.",
            ["Chủ vẫn duyệt hầu hết", "Sợ sai giá / sai thuốc"],
            ["Ít trưởng ca thật sự"],
            "Anh/chị muốn giao quyền hơn nhưng chưa yên, đúng không?",
            "Nhiều chủ muốn có người đứng được — nhưng chưa có cách thấy nhân viên đang làm tới đâu, nên vẫn ôm.",
            "Nếu giao được một việc, anh/chị muốn giao việc nào trước?",
            "Giới hạn rõ + nhìn được kết quả từng người.",
            "Phân quyền + hiệu suất ca",
            "Nhà thuốc mình đã có người đứng được khi chủ vắng chưa?",
            ["Chưa có người đủ tầm", "Sợ sai chuyên môn"],
            "phc.people_owner",
            []),
        P("PAIN-OWN-007", "owner", "Muốn nghỉ một ngày cũng khó",
            "Nghỉ là quán bị ảnh hưởng ngay.",
            ["Ít ngày nghỉ", "Nghỉ là phải nhờ người nhà"],
            ["Chủ ít đi đâu xa"],
            "Anh/chị nghỉ một ngày được không, hay quán sẽ khác ngay?",
            "Mình gặp chủ nào cũng muốn có một ngày không phải nghĩ tới quầy — nhưng thực tế nghỉ là không yên.",
            "Lần gần nhất anh/chị nghỉ cả ngày, việc gì khiến mình phải can thiệp?",
            "Quầy chạy theo việc đã chuẩn, chủ xem khi cần chứ không phải có mặt.",
            "Vận hành không phụ thuộc một người",
            "Điều gì khiến anh/chị khó nghỉ nhất?",
            ["Quán nhỏ phải trực", "Mình quen đứng rồi"],
            "phc.ops_owner",
            []),

        P("PAIN-STAFF-001", "staff", "Nhân viên mới khó vào việc",
            "Người mới mất nhiều thời gian, chủ phải kèm.",
            ["Thường xuyên tuyển", "Chủ đứng cạnh chỉ từng khách", "Người mới hay hỏi chủ"],
            ["Đang đăng tuyển", "Nhân sự mới gần đây"],
            "Nhân viên mới vào nhà thuốc, chủ lại phải đứng bên cạnh chỉ từng việc?",
            "Nhiều nhà thuốc mình gặp: nhân viên mới không phải không muốn làm, nhưng mỗi người được hướng dẫn một cách nên cuối cùng chủ vẫn phải đứng quầy hỗ trợ.",
            "Nhà thuốc mình có gặp tình trạng này không?",
            "Chuẩn hóa quy trình + hỗ trợ nhân viên trong lúc bán.",
            "Trợ lý tại quầy + quy trình chuẩn — không thay dược sĩ",
            "Người mới vào thường mất bao lâu anh/chị mới bớt phải kèm?",
            ["Ngành này phải kèm", "Người mới ít quá"],
            "phc.people_onboard",
            []),
        P("PAIN-STAFF-002", "staff", "Nhân viên hỏi đi hỏi lại",
            "Cùng một việc vẫn hỏi chủ nhiều lần.",
            ["Hỏi giá / hỏi khách quen / hỏi lấy hàng"],
            ["Chủ mệt vì câu hỏi lặp"],
            "Có việc nhân viên hỏi anh/chị đi hỏi lại không?",
            "Mình hay nghe: không phải nhân viên kém, mà câu trả lời nằm ở chủ — nên hỏi lại là nhanh hơn tìm.",
            "Câu hỏi nào anh/chị nghe lại nhiều nhất?",
            "Câu trả lời thường gặp nằm sẵn lúc đang bán.",
            "Hỗ trợ tại quầy + dữ liệu khách / hàng",
            "Anh/chị muốn giảm câu hỏi nào trước?",
            ["Hỏi cho chắc", "Mình trả lời cũng nhanh"],
            "phc.people_onboard",
            []),
        P("PAIN-STAFF-003", "staff", "Mỗi người tư vấn một kiểu",
            "Cùng một khách, hai nhân viên nói khác nhau.",
            ["Khách phàn nàn không thống nhất", "Chủ phải sửa lời nhân viên"],
            ["Nhiều người đứng quầy"],
            "Cùng một việc, nhân viên nhà thuốc mình tư vấn có giống nhau không?",
            "Nhiều chủ kể: người này nói một kiểu, người kia nói kiểu khác — khách nghe xong không biết nhà thuốc đang theo cách nào.",
            "Anh/chị có phải chỉnh lời nhân viên sau khi khách hỏi không?",
            "Cùng khung tư vấn, vẫn do người nhà thuốc quyết.",
            "Quy trình tư vấn chuẩn + hỗ trợ lúc bán",
            "Chỗ nào anh/chị thấy lệch nhau nhiều nhất?",
            ["Mỗi người có kinh nghiệm", "Khách khác thì nói khác"],
            "phc.people_consult",
            []),
        P("PAIN-STAFF-004", "staff", "Người giỏi nghỉ là mất kinh nghiệm",
            "Kinh nghiệm đi theo người, không ở lại nhà thuốc.",
            ["Người cũ nghỉ là khách hỏi lại", "Phải đào tạo lại từ đầu"],
            ["Tuyển thay người"],
            "Khi người đứng chính nghỉ, nhà thuốc mình có bị hụt không?",
            "Mình gặp nhà thuốc mất một người là mất luôn cách làm và khách quen — vì những thứ đó nằm ở người, chưa nằm ở nhà thuốc.",
            "Lần gần nhất có người nghỉ, anh/chị mất thời gian nhất ở đoạn nào?",
            "Giữ lại việc đã làm và khách đã biết, không chỉ giữ người.",
            "Dữ liệu khách + quy trình — không phụ thuộc trí nhớ một người",
            "Người nghỉ thường mang đi phần nào: khách, cách làm, hay cả hai?",
            ["Gắn bó lâu rồi", "Mình vẫn còn đứng"],
            "phc.people_turnover",
            ["staff_turnover"]),
        P("PAIN-STAFF-005", "staff", "Người mới không biết khách quen",
            "Khách cũ đến, người mới hỏi lại như khách lạ.",
            ["Khách phải tự nhắc “lần trước em mua…”"],
            ["Nhiều khách quen"],
            "Khách quen tới, nhân viên mới có nhận ra không hay hỏi lại từ đầu?",
            "Nhiều khách không trách — nhưng họ cảm thấy nhà thuốc không nhớ mình. Người mới không có chỗ để biết lần trước khách hay lấy gì.",
            "Anh/chị có hay phải nhắc nhân viên “khách này lấy cái này” không?",
            "Lịch sử mua hiện lúc khách đang đứng đó.",
            "Customer history tại quầy",
            "Khách quen nhà thuốc mình đang gắn với người bán hay với nhà thuốc?",
            ["Khách cũng kể lại được", "Quán ít khách quen"],
            "phc.customer_recall",
            []),
        P("PAIN-STAFF-006", "staff", "Khó thấy hiệu suất từng người",
            "Biết cả nhà thuốc bán, không biết từng người đang thế nào.",
            ["Khen/chê theo cảm tính", "Không biết ca nào yếu"],
            ["Nhiều ca / nhiều người"],
            "Anh/chị biết nhân viên nào đang bán tốt, hay chủ yếu cảm nhận?",
            "Nhiều chủ biết tổng ngày — nhưng hỏi “ca chiều của bạn A thế nào” thì phải đoán.",
            "Nếu nhìn được từng người, anh/chị muốn thấy điều gì trước?",
            "Nhìn ca và người theo việc thật, không phải cảm tính.",
            "KPI ca / nhân viên",
            "Hiện anh/chị đánh giá nhân viên dựa vào điều gì?",
            ["Nhìn là biết", "Sợ nhân viên so sánh nhau"],
            "phc.people_perf",
            []),
        P("PAIN-STAFF-007", "staff", "Không biết nhân viên đang kẹt chỗ nào",
            "Chỉ thấy kết quả, không thấy chỗ họ đang khó.",
            ["Sai lặp lại", "Người mới im, không hỏi"],
            ["Chủ đứng ít hơn ban ngày"],
            "Anh/chị có biết nhân viên đang gặp khó ở bước nào, hay chỉ thấy khi việc đã lệch?",
            "Mình hay thấy chủ chỉ biết khi khách phàn nàn hoặc cuối ngày lệch số — lúc đó đã muộn hơn lúc nhân viên đang kẹt.",
            "Thường anh/chị phát hiện việc lệch bằng cách nào?",
            "Thấy chỗ kẹt sớm hơn, kèm được đúng chỗ.",
            "Tín hiệu ca + hỗ trợ tại quầy",
            "Việc lệch anh/chị thường biết lúc nào trong ngày?",
            ["Mình đứng nên biết", "Nhân viên sẽ nói"],
            "phc.people_onboard",
            []),

        P("PAIN-INV-001", "inventory", "Tồn nhiều, tiền nằm im",
            "Kệ đầy nhưng vốn không xoay.",
            ["Kho chật", "Nhập theo quen"],
            ["Ít xem tồn chậm"],
            "Nhà thuốc mình có lúc nhìn kệ đầy mà vẫn thấy tiền đang nằm đó không?",
            "Nhiều nhà thuốc không thiếu hàng — mà thừa hàng không chạy. Cuối tháng mới thấy vốn bị giữ.",
            "Anh/chị có nhóm hàng nào biết là đang nằm nhưng chưa xử lý không?",
            "Nhìn sớm hàng nằm, trước khi thành đống.",
            "Tồn chậm + cảnh báo vốn",
            "Nhóm nào anh/chị đang thấy nằm nhiều nhất?",
            ["Phải dự phòng", "Nhà thuốc phải đủ hàng"],
            "phc.inv_dead",
            []),
        P("PAIN-INV-002", "inventory", "Hàng chậm không thấy sớm",
            "Biết chậm khi đã chậm lâu.",
            ["Cuối tháng mới rà", "Không có danh sách chậm"],
            ["Ít báo cáo tồn"],
            "Hàng bán chậm nhà thuốc mình thường biết lúc nào — tuần này hay cuối tháng?",
            "Mình gặp nhiều chỗ: hàng chậm không phải không biết, mà biết muộn. Lúc thấy thì đã chiếm kệ.",
            "Anh/chị đang rà hàng chậm theo cách nào?",
            "Danh sách chậm theo tuần, không đợi khóa sổ.",
            "Cảnh báo bán chậm",
            "Nếu thấy sớm hơn, anh/chị sẽ xử lý kiểu nào?",
            ["Cuối tháng xem cũng được", "Hàng chậm là bình thường"],
            "phc.inv_slow",
            []),
        P("PAIN-INV-003", "inventory", "Hết hàng đúng lúc khách hỏi",
            "Mặt đang chạy thì thiếu.",
            ["Khách hỏi không có", "Phải đi mượn / hẹn"],
            ["Bán mạnh theo đợt"],
            "Có mặt hàng khách hỏi mà nhà thuốc hết đúng lúc đó không?",
            "Nhiều chủ nói tồn thì nhiều, nhưng cái khách đang hỏi lại thiếu. Đó là chỗ mất doanh thu im lặng.",
            "Lần gần nhất hết hàng lúc khách hỏi, đó là nhóm nào?",
            "Giữ hàng đang chạy, không chỉ giữ hàng cho đủ kệ.",
            "Cảnh báo sắp hết + nhu cầu",
            "Anh/chị biết mặt nào hay hết bất ngờ không?",
            ["Nhà cung cấp chậm", "Khách hỏi ít"],
            "phc.inv_stockout",
            []),
        P("PAIN-INV-004", "inventory", "Khó nắm hạn dùng",
            "Cận date lộ muộn.",
            ["Rà hạn thủ công", "Đôi khi phát hiện khi sắp hết hạn"],
            ["Nhiều lô / nhiều date"],
            "Hạn dùng nhà thuốc mình đang nắm theo tuần hay khi đứng trước kệ mới thấy?",
            "Nỗi đau mình hay nghe: không phải không biết cận date, mà biết lúc đã sát — xử lý thì trễ.",
            "Anh/chị đang rà hạn dùng thế nào?",
            "Thấy cận date sớm, theo lô.",
            "Cảnh báo hạn + FEFO",
            "Nhóm nào nhà thuốc hay bị cận date nhất?",
            ["Mình nhớ được", "Hàng ít date"],
            "phc.inv_expiry",
            ["near_expiry"]),
        P("PAIN-INV-005", "inventory", "Lấy hàng chưa theo FEFO",
            "Lô mới ra trước, lô cũ nằm lại.",
            ["Nhân viên lấy hàng gần tay", "Lô cũ bị quên"],
            ["Nhiều lô một SKU"],
            "Nhân viên lấy hàng có đang lấy lô gần hết hạn trước không?",
            "Nhiều nhà thuốc biết nguyên tắc — nhưng lúc đông khách, người ta lấy hàng gần nhất. Lô cũ ở lại.",
            "Anh/chị có phải nhắc việc này không?",
            "Gợi ý lô lúc lấy hàng, không chỉ nhắc miệng.",
            "FEFO tại lúc bán / xuất",
            "Việc lấy sai lô nhà thuốc mình phát hiện lúc nào?",
            ["Mình sắp kệ rồi", "Ít lô"],
            "phc.inv_fefo",
            []),
        P("PAIN-INV-006", "inventory", "Tồn trên sổ và kệ lệch",
            "Số một đằng, kệ một nẻo.",
            ["Kiểm kê bất ngờ", "Phải chỉnh tay"],
            ["Kiểm kê đau"],
            "Lúc kiểm kê, nhà thuốc mình có hay lệch giữa sổ và kệ không?",
            "Mình nghe nhiều: không phải gian lận — mà xuất nhập không khớp lúc bán, nên kiểm kê thành trận đánh.",
            "Lệch thường ở nhóm nào?",
            "Bán và tồn cùng một sự thật.",
            "Xuất nhập gắn ca + kiểm lệch",
            "Lần kiểm gần nhất lệch làm anh/chị mất thời gian thế nào?",
            ["Lệch nhỏ", "Mình chấp nhận"],
            "phc.inv_variance",
            []),
        P("PAIN-INV-007", "inventory", "Không biết mặt nào đang hiệu quả",
            "Bán được nhưng không biết mặt nào kéo.",
            ["Nhập theo cảm tính", "Kệ nhiều nhưng ít mặt chạy"],
            ["Ít xem top/slow"],
            "Anh/chị biết mặt nào đang kéo nhà thuốc, hay chủ yếu nhớ những mặt hay bán?",
            "Nhiều chỗ nhớ 10 mặt quen — còn cả kệ còn lại thì “thấy cũng bán”. Khó quyết giữ hay bỏ.",
            "Nếu chọn 10 mặt nhìn trước mỗi tuần, anh/chị muốn nhìn theo doanh thu hay theo tồn?",
            "Top / chậm tách rõ, để quyết nhập.",
            "Hiệu quả SKU",
            "Anh/chị đang quyết nhập chủ yếu dựa vào điều gì?",
            ["Kinh nghiệm", "Trình dược"],
            "phc.inv_mix",
            []),
        P("PAIN-INV-008", "inventory", "Nhập hàng theo kinh nghiệm",
            "Nhập vì quen, vì trình, vì sợ thiếu.",
            ["Đơn nhập lặp", "Ít đối chiếu bán thật"],
            ["Nhà cung cấp tới là ký"],
            "Khi nhập, anh/chị dựa nhiều vào số đang bán hay vào cảm giác “phải có”?",
            "Mình gặp nhà thuốc nhập không sai — nhưng nhập theo thói quen, nên vốn đi vào chỗ không chạy.",
            "Anh/chị có xem bán/tồn trước khi ký đơn không?",
            "Nhập bám nhu cầu thật, không chỉ thói quen.",
            "Gợi ý nhập theo bán + tồn + cận date",
            "Phần nhập nào anh/chị thấy khó từ chối nhất?",
            ["Phải đủ hàng", "Quan hệ nhà cung cấp"],
            "phc.inv_purchase",
            []),

        P("PAIN-CUST-001", "customer", "Nhiều khách cũ nhưng không biết họ là ai",
            "Đông khách, ít hồ sơ.",
            ["Bán xong là hết", "Không gọi được tên"],
            ["Ít lấy SĐT"],
            "Khách cũ nhà thuốc mình có đang là một danh sách, hay chỉ là người hay tới?",
            "Nhiều nhà thuốc có khách quen thật — nhưng hỏi “họ là ai, lần trước lấy gì” thì không nằm đâu cả.",
            "Anh/chị đang nhớ khách quen bằng cách nào?",
            "Khách thành hồ sơ nhà thuốc, không chỉ khuôn mặt.",
            "Customer + lần mua",
            "Nhà thuốc mình đang giữ được thông tin gì của khách cũ?",
            ["Khách không muốn để SĐT", "Quán nhỏ nhớ mặt"],
            "phc.customer_id",
            []),
        P("PAIN-CUST-002", "customer", "Mua xong rồi mất liên hệ",
            "Sau bán không còn đường nhắc.",
            ["Không follow", "Khách hết thuốc là thôi"],
            ["Ít chăm sóc sau bán"],
            "Khách mua xong, nhà thuốc mình còn đường nào để nhắc lại không?",
            "Lúc quầy vắng thường lộ phần sau bán: khách lấy thuốc rồi ít được nhắc. Không phải họ không cần — nhà thuốc không còn chỗ để nhớ.",
            "Anh/chị có nhóm khách nào biết là nên nhắc nhưng chưa nhắc được không?",
            "Nhắc đúng người, đúng việc đã mua — không nhắn đại.",
            "Lịch sử mua + chăm sóc sau bán",
            "Nhà thuốc mình có gặp tình trạng này không?",
            ["Sợ làm phiền", "Không có người nhắn"],
            "phc.customer_after",
            ["after_sale"]),
        P("PAIN-CUST-003", "customer", "Không biết khách thường lấy gì",
            "Khách tới, phải hỏi lại từ đầu.",
            ["Không có lịch sử trên quầy", "Chủ nhớ một ít khách"],
            ["Bán nhanh, ít ghi"],
            "Khi khách quen tới, nhân viên có thấy lần trước họ lấy gì không?",
            "Nhiều nhà thuốc bán đều — nhưng “khách này hay lấy gì” nằm ở người đứng lâu, không nằm ở quầy.",
            "Anh/chị có phải nhắc nhân viên về khách quen không?",
            "Lịch sử hiện lúc đang bán.",
            "Lịch sử mua tại quầy",
            "Khách nào anh/chị nhớ rõ nhất — và còn bao nhiêu người không nhớ?",
            ["Hỏi lại cũng được", "Khách tự nói"],
            "phc.customer_history",
            []),
        P("PAIN-CUST-004", "customer", "Không biết ai lâu chưa quay lại",
            "Mất khách im lặng.",
            ["Không có danh sách ngủ", "Chỉ thấy hôm nay vắng"],
            ["Trước đông, nay thưa"],
            "Anh/chị có biết khách nào lâu rồi chưa tới, hay chỉ thấy hôm nay quầy vắng?",
            "Mình hay thấy nhà thuốc mất khách không phải vì một sự cố — mà vì không ai để ý họ đã ngừng tới.",
            "Nếu có 20 khách lâu chưa lại, anh/chị có muốn biết không?",
            "Thấy khách ngủ sớm, trước khi thành mất hẳn.",
            "Khách lâu không mua",
            "Nhà thuốc mình có hay bất ngờ thấy vắng hơn trước không?",
            ["Khách tự quay lại", "Không muốn soi khách"],
            "phc.customer_lapse",
            []),
        P("PAIN-CUST-005", "customer", "Khách quen gắn nhân viên hơn nhà thuốc",
            "Người nghỉ là khách đi theo.",
            ["Khách hỏi “bạn A còn không”", "Ít hồ sơ chung"],
            ["Một người đứng chính"],
            "Khách quen nhà thuốc mình đang nhớ người bán hay nhớ nhà thuốc?",
            "Đây là chỗ nhiều chủ giật mình: khách không bỏ nhà thuốc — họ bỏ người họ quen. Người đó nghỉ là mối quan hệ đứt.",
            "Anh/chị có khách nào chỉ chịu một nhân viên không?",
            "Quan hệ khách thuộc nhà thuốc, người bán vẫn là người bán.",
            "Hồ sơ khách chung + lịch sử",
            "Nếu người đứng chính nghỉ, anh/chị lo phần khách thế nào?",
            ["Mình cũng quen khách", "Chưa xảy ra"],
            "phc.customer_id",
            []),
        P("PAIN-CUST-006", "customer", "Chăm sóc khách chưa có dữ liệu",
            "Chăm theo đợt, không theo người.",
            ["Nhắn chung", "Không biết ai cần gì"],
            ["Có Zalo, ít danh sách"],
            "Khi nhà thuốc mình chăm khách, có đang biết từng người cần gì không?",
            "Nhiều chỗ có nhắn tin — nhưng nhắn một nội dung cho nhiều người. Khách thấy không phải chuyện của mình.",
            "Anh/chị đang chăm khách theo dịp hay theo việc họ đã mua?",
            "Chăm theo lịch sử, không theo chiến dịch chung.",
            "CSKH dựa trên mua hàng",
            "Phần chăm sóc nào anh/chị thấy đang làm mà chưa chắc đúng người?",
            ["Không muốn làm phiền", "Chưa có người phụ trách"],
            "phc.customer_care",
            []),
        P("PAIN-CUST-007", "customer", "Khó nhắc khách mua lại",
            "Biết nên nhắc, không biết nhắc ai / lúc nào.",
            ["Hết liệu trình không hay", "Sợ nhắn nhầm"],
            ["Thuốc dùng theo đợt"],
            "Anh/chị có khách nên được nhắc nhưng nhà thuốc chưa nhắc được không?",
            "Mình gặp nhiều: không phải không muốn chăm — mà sợ nhắn nhầm người, nhắn lúc không hợp, hoặc không biết lần trước họ lấy gì.",
            "Nếu nhắc được đúng người, anh/chị muốn bắt đầu với nhóm nào?",
            "Nhắc đúng việc đã mua, đúng lúc sau bán.",
            "After-sale theo lịch sử",
            "Nhà thuốc mình ngại nhắc vì lý do nào nhất?",
            ["Sợ spam", "Không có SĐT"],
            "phc.customer_after",
            []),
        P("PAIN-CUST-008", "customer", "Lịch sử mua chưa dùng được",
            "Có bán nhưng không đọc lại được.",
            ["Hóa đơn rời", "Không xem theo khách"],
            ["Có phần mềm ghi đơn"],
            "Lịch sử bán nhà thuốc mình có xem lại theo từng khách được không?",
            "Nhiều nhà thuốc có đơn — nhưng đơn để tính tiền, không để hiểu khách. Lần sau vẫn hỏi như lần đầu.",
            "Anh/chị đã từng mở lại đơn cũ của một khách để quyết việc hôm nay chưa?",
            "Lịch sử phục vụ lần gặp này, không chỉ để lưu.",
            "Lịch sử mua dùng lúc bán",
            "Hiện anh/chị xem lại đơn cũ lúc nào?",
            ["Đơn chỉ để thuế", "Không kịp xem"],
            "phc.customer_history",
            []),

        P("PAIN-REV-001", "revenue", "Biết doanh thu, chưa biết vì sao",
            "Có số tổng, thiếu nguyên nhân.",
            ["Cuối ngày chỉ nhìn tổng", "Không tách được lý do tăng/giảm"],
            ["Ít xem theo nhóm"],
            "Cuối ngày anh/chị thấy số — có biết hôm nay khỏe/yếu vì đâu không?",
            "Nhiều nhà thuốc biết bán được bao nhiêu. Khó hơn là biết vì sao hôm nay khác hôm qua.",
            "Khi số giảm, anh/chị thường đoán nguyên nhân thế nào?",
            "Tách được nhóm / ca / việc kéo số.",
            "Analytics nguyên nhân, không chỉ tổng",
            "Anh/chị muốn hiểu số theo tuần hay theo từng ngày?",
            ["Tổng là đủ", "Mình cảm nhận được"],
            "phc.rev_why",
            []),
        P("PAIN-REV-002", "revenue", "Không biết nhóm nào đang kéo",
            "Bán đều kệ, không biết trụ cột.",
            ["Không có mix", "Nhập dàn trải"],
            ["Nhiều nhóm hàng"],
            "Anh/chị biết nhóm nào đang kéo nhà thuốc, hay tất cả đều “cũng bán”?",
            "Mình hay thấy chủ nhớ vài mặt mạnh — còn cả nhóm thì mơ hồ. Khó quyết tập trung.",
            "Nếu chỉ nhìn 3 nhóm, anh/chị nghĩ nhóm nào đang gánh?",
            "Mix rõ, để nuôi đúng chỗ kéo.",
            "Doanh thu theo nhóm",
            "Nhóm nào anh/chị đang đầu tư nhiều nhất?",
            ["Phải đủ nhóm", "Trình dược đưa nhiều"],
            "phc.rev_mix",
            []),
        P("PAIN-REV-003", "revenue", "Không biết ai đang bán tốt",
            "Tổng đẹp, người không rõ.",
            ["Thưởng cảm tính", "Ca mạnh/yếu đoán"],
            ["Nhiều nhân viên"],
            "Doanh thu nhà thuốc mình có gắn được với từng người đứng ca không?",
            "Nhiều chủ khen người “chăm” — nhưng số thì cả nhà thuốc. Khó biết ai đang kéo, ai đang kẹt.",
            "Anh/chị đang chia việc / thưởng dựa vào gì?",
            "Số theo người và ca, để kèm đúng chỗ.",
            "Doanh thu theo nhân viên",
            "Nếu thấy một người yếu số, anh/chị sẽ làm gì trước?",
            ["Sợ so sánh", "Mình đứng nên biết"],
            "phc.rev_people",
            []),
        P("PAIN-REV-004", "revenue", "Không biết giờ nào bán tốt",
            "Xếp ca theo thói quen.",
            ["Đông/vắng đoán", "Người giỏi xếp giờ trống"],
            ["Nhiều ca"],
            "Anh/chị biết khung giờ nào nhà thuốc đang khỏe nhất không?",
            "Mình gặp chỗ xếp người mạnh vào giờ quen của chủ — không phải giờ khách đông. Số cả ngày bị kéo xuống im.",
            "Giờ nào anh/chị thấy đông thật, và giờ nào đang để trống người?",
            "Xếp ca theo giờ thật, không theo thói quen.",
            "Doanh thu theo giờ",
            "Anh/chị xếp ca hiện dựa vào điều gì?",
            ["Giờ mở cửa cố định", "Người xin ca"],
            "phc.rev_hour",
            []),
        P("PAIN-REV-005", "revenue", "Không biết khách nào có giá trị",
            "Đối xử gần như nhau.",
            ["Không có nhóm khách", "Chăm đều hoặc không chăm"],
            ["Có khách mua lớn"],
            "Anh/chị có biết khách nào đang giữ doanh thu nhà thuốc không?",
            "Nhiều chỗ 20% khách im lặng gánh phần lớn — nhưng nhà thuốc không gọi tên được họ.",
            "Nếu biết 20 khách quan trọng, anh/chị sẽ làm gì khác?",
            "Nhìn khách theo giá trị thật, để giữ đúng người.",
            "Giá trị khách",
            "Nhà thuốc mình đang giữ khách lớn bằng cách nào?",
            ["Khách lớn cũng chỉ ghé", "Không muốn phân biệt"],
            "phc.rev_value",
            []),
        P("PAIN-REV-006", "revenue", "Khó thấy chỗ số đang tụt",
            "Giảm từ từ, không biết lỗ chỗ nào.",
            ["So với tháng trước mơ hồ", "Không có điểm rơi"],
            ["Cảm giác kém hơn năm ngoái"],
            "Khi cảm thấy kém hơn trước, anh/chị biết đang tụt ở nhóm nào không?",
            "Mình hay nghe “năm nay chậm hơn” — nhưng chậm ở khách, ở nhóm hàng, hay ở ca thì chưa tách.",
            "Anh/chị so số theo tháng hay theo cảm giác?",
            "Thấy điểm rơi trước khi thành “cả năm chậm”.",
            "So sánh + điểm giảm",
            "Chỗ nào anh/chị đang nghi đang yếu?",
            ["Thị trường chung", "Chưa rà"],
            "phc.rev_drop",
            []),

        P("PAIN-DATA-001", "data", "Có phần mềm vẫn phải hỏi nhân viên",
            "Máy có số, chủ vẫn hỏi miệng.",
            ["Hỏi “hôm nay sao”", "Không mở báo cáo"],
            ["Đã dùng phần mềm"],
            "Cuối ngày anh/chị mở số trên máy hay hỏi nhân viên “hôm nay thế nào”?",
            "Nhiều nhà thuốc có phần mềm — nhưng chủ vẫn hỏi miệng, vì số trên máy chưa thành câu trả lời.",
            "Anh/chị hỏi nhân viên điều gì mà máy chưa trả lời được?",
            "Số phải trả lời được câu chủ đang hỏi.",
            "Lớp quản trị + insight, không chỉ ghi nhận",
            "Câu nào anh/chị hay hỏi nhân viên nhất?",
            ["Hỏi cho nhanh", "Máy khó xem"],
            "phc.data_ask",
            []),
        P("PAIN-DATA-002", "data", "Có dữ liệu nhưng chưa ra quyết định",
            "Đầy số, ít việc làm tiếp.",
            ["Báo cáo để đó", "Quyết vẫn theo cảm"],
            ["Export nhiều"],
            "Số nhà thuốc mình đang giúp anh/chị quyết việc tuần này, hay chủ yếu để lưu?",
            "Mình gặp chỗ không thiếu dữ liệu. Thiếu bước “vậy tuần này làm gì”.",
            "Tuần này anh/chị đã quyết một việc dựa trên số chưa?",
            "Mỗi số gắn một việc tiếp theo.",
            "Insight → next action",
            "Quyết định nào anh/chị đang muốn có số để chốt?",
            ["Mình quyết bằng kinh nghiệm", "Số không tin"],
            "phc.data_decide",
            []),
        P("PAIN-DATA-003", "data", "Báo cáo nhiều nhưng khó đọc",
            "Mở ra rối, đóng lại hỏi miệng.",
            ["Nhiều cột", "Không biết xem trang nào"],
            ["Có báo cáo sẵn"],
            "Báo cáo nhà thuốc mình anh/chị xem được ngay, hay mở ra rồi thôi?",
            "Nỗi đau em đang đi: không phải thiếu báo cáo — mà báo cáo không thành một câu rõ cho chủ.",
            "Anh/chị muốn thấy gì trong 30 giây cuối ngày?",
            "Ít số, đúng câu hỏi của chủ.",
            "Báo cáo tóm tắt theo vai trò chủ",
            "Nhà thuốc mình có gặp tình trạng này không?",
            ["Không rành máy", "Báo cáo cho kế toán"],
            "phc.data_report",
            ["reporting"]),
        P("PAIN-DATA-004", "data", "Cuối tháng mới nhìn lại",
            "Biết muộn thì đã qua.",
            ["Chờ khóa sổ", "Không xem trong tuần"],
            ["Kế toán làm tháng"],
            "Anh/chị nhìn nhà thuốc theo tuần hay đợi cuối tháng?",
            "Nhiều việc lệch (hàng chậm, khách ngủ, ca yếu) nếu đợi cuối tháng thì chỉ còn giải thích, không còn chỉnh.",
            "Nếu xem một lần giữa tháng, anh/chị muốn xem gì trước?",
            "Nhịp tuần, không chỉ sổ tháng.",
            "Tóm tắt tuần",
            "Cuối tháng anh/chị thường bất ngờ vì chuyện gì?",
            ["Tháng mới đủ số", "Không có thời gian xem"],
            "phc.data_cadence",
            []),
        P("PAIN-DATA-005", "data", "Thông tin nằm trong đầu chủ",
            "Mất chủ là mất cách đọc nhà thuốc.",
            ["Chỉ chủ giải thích được số", "Người khác không đọc được"],
            ["Chủ ôm hết"],
            "Người khác trong nhà thuốc có đọc được tình hình như anh/chị không?",
            "Mình thấy “số” đôi khi vẫn nằm trong đầu chủ: chỉ mình biết hôm nay thế nào mới là đúng.",
            "Nếu anh/chị vắng, ai đọc được nhà thuốc?",
            "Cùng một bức tranh, không chỉ trong đầu một người.",
            "Tóm tắt chung + vai trò",
            "Phần nào chỉ anh/chị đang giữ trong đầu?",
            ["Mình phải nắm", "Người khác không cần"],
            "phc.data_owner",
            []),
        P("PAIN-DATA-006", "data", "Việc hàng ngày chưa thành chuẩn",
            "Mỗi ca làm một kiểu.",
            ["Mở/đóng ca khác nhau", "Ghi chép rời"],
            ["Ít checklist"],
            "Việc mở ca / giao ca / đóng ngày nhà thuốc mình đang làm giống nhau giữa các ca không?",
            "Nhiều nhà thuốc bán được — nhưng việc quanh bán (giao ca, kiểm, nhắc) mỗi người một kiểu.",
            "Ca nào anh/chị thấy làm khác ca khác nhiều nhất?",
            "Việc lặp thành chuẩn, ca nào cũng làm được.",
            "Chuẩn hóa vận hành",
            "Anh/chị muốn chuẩn ca nào trước?",
            ["Quán nhỏ không cần", "Mình hướng dẫn miệng"],
            "phc.ops_standard",
            []),

        P("PAIN-GROW-001", "growth", "Một cơ sở còn ổn, thêm cơ sở bắt đầu khó",
            "Nhân lên là mất tầm nhìn.",
            ["Cơ sở 2 không giống cơ sở 1", "Chủ chạy giữa các điểm"],
            ["Đã có / sắp có cơ sở 2"],
            "Nếu thêm một điểm, anh/chị có còn nắm được như điểm này không?",
            "Mình gặp nhiều: một nhà thuốc chủ nắm được. Sang điểm hai, cách nắm đó không đi theo.",
            "Anh/chị đang nghĩ tới điểm tiếp theo chưa — và lo nhất điều gì?",
            "Cùng một cách nhìn cho mọi điểm.",
            "Nhìn nhiều cơ sở một chỗ",
            "Điểm nào anh/chị sợ mất kiểm soát nhất nếu mở thêm?",
            ["Chưa tính mở", "Sẽ cho người nhà đứng"],
            "phc.growth_multi",
            []),
        P("PAIN-GROW-002", "growth", "Muốn mở nhưng sợ không kiểm được",
            "Muốn lớn, sợ loang.",
            ["Chưa chốt điểm mới", "Sợ nhân sự / kho"],
            ["Đang tìm mặt bằng"],
            "Anh/chị muốn mở thêm nhưng còn điểm nào khiến mình chưa dám?",
            "Nhiều chủ không thiếu ý chí mở. Họ thiếu cảm giác “mình vẫn nắm được nếu không đứng đó mỗi ngày”.",
            "Điểm nào đang khiến anh/chị chưa dám: người, kho, hay số?",
            "Mở khi đã thấy điểm hiện tại chạy không cần mình đứng suốt.",
            "Sẵn sàng mở rộng + kiểm soát tập trung",
            "Nhà thuốc hiện tại anh/chị đã nghỉ được một ngày chưa?",
            ["Thị trường khó", "Vốn chưa sẵn"],
            "phc.growth_ready",
            []),
        P("PAIN-GROW-003", "growth", "Chưa biết đã sẵn sàng mở chưa",
            "Muốn mở, không có checklist.",
            ["Quyết theo cảm", "Chưa đo điểm hiện tại"],
            ["Đang bàn với gia đình"],
            "Anh/chị biết nhà thuốc hiện tại đã sẵn sàng để nhân bản chưa?",
            "Mình hay hỏi: điểm này đã chạy khi chủ vắng chưa? Nếu chưa, điểm sau sẽ copy đúng chỗ đang yếu.",
            "Theo anh/chị, dấu hiệu nào cho thấy “được rồi, mở được”?",
            "Đo sẵn sàng trước khi ký mặt bằng.",
            "Health check vận hành trước khi nhân",
            "Anh/chị đang nghiêng mở hay đang dừng lại?",
            ["Chưa nghĩ", "Mở là chuyện sau"],
            "phc.growth_ready",
            []),
        P("PAIN-GROW-004", "growth", "Khó đồng bộ người giữa các điểm",
            "Mỗi điểm một cách làm.",
            ["Đào tạo lại từng điểm", "Người giỏi kẹt một chỗ"],
            ["Đã có 2+ điểm"],
            "Nhân viên các điểm nhà thuốc mình đang làm theo cùng một cách không?",
            "Sang điểm hai, nhiều chủ phát hiện mình đang quản hai nhà thuốc — không phải một hệ thống hai cửa.",
            "Chỗ nào đang lệch giữa các điểm?",
            "Cùng quy trình, khác địa điểm.",
            "Chuẩn hóa đa điểm + người",
            "Điểm nào đang làm khác điểm chính?",
            ["Mỗi quán một kiểu khách", "Người khác nhau"],
            "phc.growth_people",
            []),
        P("PAIN-GROW-005", "growth", "Kho nhiều điểm khó nắm",
            "Điểm này thừa, điểm kia thiếu.",
            ["Chuyển hàng miệng", "Không thấy tồn chung"],
            ["Nhiều kho / quầy"],
            "Hàng giữa các điểm nhà thuốc mình đang thấy chung được không?",
            "Mình gặp: một điểm ế đúng mặt điểm kia đang hết. Chủ biết lúc nhân viên gọi sang mượn.",
            "Anh/chị đang điều hàng giữa các điểm thế nào?",
            "Tồn chung, điều được, không mượn miệng.",
            "Kho đa điểm",
            "Lần gần nhất chuyển hàng vì một điểm hết, mất bao lâu?",
            ["Gần nên chạy sang", "Mỗi điểm tự nhập"],
            "phc.growth_stock",
            []),

        P("PAIN-TECH-001", "tech", "Máy ghi nhận, chủ vẫn quản bằng miệng",
            "Phần mềm có mặt, quản trị vẫn ở người.",
            ["Nhập đơn xong không xem", "Chủ điều bằng điện thoại"],
            ["Đã có POS / phần mềm"],
            "Phần mềm nhà thuốc mình đang giúp anh/chị quản, hay chủ yếu để bán?",
            "Nhiều nhà thuốc không thiếu phần mềm. Thiếu lớp biến việc đã bán thành việc chủ nắm được.",
            "Anh/chị mở phần mềm để bán hay để xem nhà thuốc?",
            "Lớp quản trị trên dữ liệu đang có.",
            "Management layer + insight",
            "Anh/chị muốn máy trả lời câu nào trước?",
            ["Máy đủ rồi", "Nhân viên không dùng"],
            "phc.tech_layer",
            []),
        P("PAIN-TECH-002", "tech", "Nhiều số, không biết xem gì trước",
            "Mở báo cáo là lạc.",
            ["Nhiều menu", "Không có trang “hôm nay”"],
            ["Phần mềm nhiều chức năng"],
            "Anh/chị biết mình nên xem gì trước mỗi ngày không?",
            "Không phải thiếu số. Là không biết số nào đáng xem lúc 20:00 khi vừa đóng cửa.",
            "Nếu chỉ một trang cuối ngày, anh/chị muốn thấy 3 dòng nào?",
            "Một trang cho chủ, không phải cả menu.",
            "Tóm tắt ngày cho chủ",
            "Hiện anh/chị xem gì trước khi về?",
            ["Không xem", "Xem tổng tiền"],
            "phc.tech_focus",
            []),
        P("PAIN-TECH-003", "tech", "Phần mềm chưa giúp ra quyết định tuần",
            "Cuối tuần vẫn quyết như chưa có máy.",
            ["Không có việc gợi ý", "Số không thành việc"],
            ["Dùng máy đã lâu"],
            "Cuối tuần anh/chị có một việc rõ để làm từ số không, hay vẫn quyết như trước?",
            "Mình phân biệt: máy ghi nhận là một việc. Máy giúp chọn việc tuần sau là việc khác.",
            "Tuần tới anh/chị muốn máy gợi ý việc gì?",
            "Từ số ra một việc tiếp theo.",
            "Next action từ dữ liệu",
            "Anh/chị đang quyết việc tuần dựa vào đâu?",
            ["Kinh nghiệm", "Người nhà bàn"],
            "phc.tech_decide",
            []),
    ];

    private static NovixaPainDef P(
        string code,
        string category,
        string name,
        string description,
        string[] symptoms,
        string[] signals,
        string hook,
        string outreach,
        string question,
        string solutionDirection,
        string solutionMapping,
        string cta,
        string[] objections,
        string phcMapping,
        string[] aliases) =>
        new(code, category, name, description, symptoms, signals, hook, outreach, question,
            solutionDirection, solutionMapping, cta, objections, phcMapping, aliases);
}

internal sealed record NovixaPainDef(
    string Code,
    string Category,
    string Name,
    string Description,
    IReadOnlyList<string> Symptoms,
    IReadOnlyList<string> Signals,
    string Hook,
    string Outreach,
    string Question,
    string SolutionDirection,
    string SolutionMapping,
    string Cta,
    IReadOnlyList<string> Objections,
    string PhcMapping,
    IReadOnlyList<string> Aliases);
