export const IMAGE_DIRECTOR_REVIEW_ID = 'PRODUCTION_IMAGE_DIRECTOR_REVIEW_V1';

export const IMAGE_DIRECTOR_REVIEW_STATUSES = ['PENDING', 'APPROVED', 'REJECTED', 'SUPERSEDED'] as const;

export const IMAGE_DIRECTOR_REVIEW_PIPELINE = [
  'LOCKED MASTER',
  'LOCKED DNA',
  'LOCKED PRP',
  'IDENTITY GOVERNANCE PASS',
  'DIRECTOR APPROVED SHOT CONTRACT',
  'COMPILED PROMPT',
  'DIRECTOR APPROVED IMAGE GENERATION CONTRACT',
  'IMAGE GENERATION EXECUTION',
  'TECHNICAL QA',
  'CHARACTER QA',
  'IDENTITY QA',
  'CONTINUITY QA',
  'COMPOSITION QA',
  'READY_FOR_DIRECTOR',
  'PRODUCTION IMAGE DIRECTOR REVIEW',
] as const;
