export const PRODUCTION_PROMPT_COMPILER_ID = 'PRODUCTION_PROMPT_COMPILER_V1';

export const PROMPT_COMPILER_STATUSES = ['NOT_READY', 'BLOCKED', 'COMPILED', 'SUPERSEDED'] as const;

export const PROMPT_SECTIONS = [
  'IDENTITY',
  'SCENE',
  'STORY BEAT',
  'CHARACTER STATE',
  'WARDROBE',
  'PROPS',
  'COMPOSITION',
  'LIGHTING',
  'MOTION INTENT',
  'CONTINUITY',
  'PRODUCTION REQUIREMENTS',
  'MANDATORY CONSTRAINTS',
  'FORBIDDEN CONSTRAINTS',
] as const;
