export const IMAGE_GENERATION_CONTRACT_ID = 'PRODUCTION_IMAGE_GENERATION_CONTRACT_V1';

export const IMAGE_GENERATION_CONTRACT_STATUSES = [
  'DRAFT',
  'VALIDATED',
  'DIRECTOR_APPROVED',
  'REJECTED',
  'SUPERSEDED',
] as const;
