export const PRODUCTION_VIDEO_CONTRACT_ID = 'PRODUCTION_VIDEO_CONTRACT_V1';

export const PRODUCTION_VIDEO_CONTRACT_STATUSES = [
  'DRAFT',
  'VALIDATED',
  'DIRECTOR_APPROVED',
  'REJECTED',
  'SUPERSEDED',
] as const;

export const PRODUCTION_VIDEO_CONTRACT_PIPELINE = [
  'LOCKED MASTER',
  'LOCKED DNA',
  'LOCKED PRP',
  'IDENTITY GOVERNANCE PASS',
  'DIRECTOR APPROVED SHOT CONTRACT',
  'COMPILED PROMPT',
  'DIRECTOR APPROVED IMAGE GENERATION CONTRACT',
  'IMAGE EXECUTION',
  'IMAGE QA',
  'DIRECTOR APPROVED STILL',
  'VIDEO CONTRACT',
  'DIRECTOR VIDEO CONTRACT REVIEW',
  'VIDEO CONTRACT APPROVED',
] as const;
