export const IMAGE_GENERATION_EXECUTION_ID = 'PRODUCTION_IMAGE_GENERATION_EXECUTION_V1';

export const IMAGE_GENERATION_EXECUTION_STATUSES = [
  'PREFLIGHT',
  'BLOCKED',
  'REQUESTED',
  'ACCEPTED',
  'PROCESSING',
  'SUCCEEDED',
  'FAILED',
  'QA_FAILED',
  'READY_FOR_DIRECTOR',
  'APPROVED',
  'REJECTED',
  'IMAGE_APPROVED',
  'IMAGE_REJECTED',
] as const;
