export const VIDEO_GENERATION_EXECUTION_ID = 'PRODUCTION_VIDEO_GENERATION_EXECUTION_V1';

export const VIDEO_GENERATION_EXECUTION_STATUSES = [
  'PREFLIGHT',
  'BLOCKED',
  'REQUESTED',
  'ACCEPTED',
  'PROCESSING',
  'SUCCEEDED',
  'FAILED',
  'QA_FAILED',
  'READY_FOR_DIRECTOR',
  'DIRECTOR_APPROVED',
  'DIRECTOR_REJECTED',
] as const;
